# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\account.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountDialog(object):
    def setupUi(self, AccountDialog):
        AccountDialog.setObjectName("AccountDialog")
        AccountDialog.setWindowModality(QtCore.Qt.NonModal)
        AccountDialog.resize(480, 270)
        self.label_accountInfo = QtWidgets.QLabel(AccountDialog)
        self.label_accountInfo.setGeometry(QtCore.QRect(0, 10, 480, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accountInfo.setFont(font)
        self.label_accountInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accountInfo.setObjectName("label_accountInfo")
        self.label_accountID = QtWidgets.QLabel(AccountDialog)
        self.label_accountID.setGeometry(QtCore.QRect(30, 60, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_accountID.setFont(font)
        self.label_accountID.setObjectName("label_accountID")
        self.text_accountID = QtWidgets.QLineEdit(AccountDialog)
        self.text_accountID.setEnabled(True)
        self.text_accountID.setGeometry(QtCore.QRect(65, 60, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_accountID.setFont(font)
        self.text_accountID.setText("")
        self.text_accountID.setCursorPosition(0)
        self.text_accountID.setAlignment(QtCore.Qt.AlignCenter)
        self.text_accountID.setReadOnly(True)
        self.text_accountID.setObjectName("text_accountID")
        self.label_passwordNew = QtWidgets.QLabel(AccountDialog)
        self.label_passwordNew.setGeometry(QtCore.QRect(30, 110, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_passwordNew.setFont(font)
        self.label_passwordNew.setObjectName("label_passwordNew")
        self.button_save = QtWidgets.QPushButton(AccountDialog)
        self.button_save.setEnabled(False)
        self.button_save.setGeometry(QtCore.QRect(180, 200, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setStyleSheet("#button_save{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_save:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_save:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_save:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_save.setObjectName("button_save")
        self.label_passwordRe = QtWidgets.QLabel(AccountDialog)
        self.label_passwordRe.setGeometry(QtCore.QRect(30, 150, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_passwordRe.setFont(font)
        self.label_passwordRe.setObjectName("label_passwordRe")
        self.text_passwordRe = QtWidgets.QLineEdit(AccountDialog)
        self.text_passwordRe.setGeometry(QtCore.QRect(190, 150, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_passwordRe.setFont(font)
        self.text_passwordRe.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.text_passwordRe.setText("")
        self.text_passwordRe.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_passwordRe.setCursorPosition(0)
        self.text_passwordRe.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_passwordRe.setObjectName("text_passwordRe")
        self.text_passwordNew = QtWidgets.QLineEdit(AccountDialog)
        self.text_passwordNew.setGeometry(QtCore.QRect(190, 110, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_passwordNew.setFont(font)
        self.text_passwordNew.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.text_passwordNew.setText("")
        self.text_passwordNew.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_passwordNew.setCursorPosition(0)
        self.text_passwordNew.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_passwordNew.setObjectName("text_passwordNew")
        self.button_pwVisibility = QtWidgets.QPushButton(AccountDialog)
        self.button_pwVisibility.setGeometry(QtCore.QRect(420, 110, 30, 30))
        self.button_pwVisibility.setStyleSheet("image: url(:/icons/icons/show.png);\n"
"color: rgb(0, 0, 0); \n"
"background-color: rgba(255, 255, 255, 0);\n"
"border:0px;")
        self.button_pwVisibility.setText("")
        self.button_pwVisibility.setIconSize(QtCore.QSize(30, 30))
        self.button_pwVisibility.setFlat(True)
        self.button_pwVisibility.setObjectName("button_pwVisibility")
        self.button_pwReVisibility = QtWidgets.QPushButton(AccountDialog)
        self.button_pwReVisibility.setGeometry(QtCore.QRect(420, 150, 30, 30))
        self.button_pwReVisibility.setStyleSheet("image: url(:/icons/icons/show.png);\n"
"color: rgb(0, 0, 0); \n"
"background-color: rgba(255, 255, 255, 0);\n"
"border:0px;")
        self.button_pwReVisibility.setText("")
        self.button_pwReVisibility.setIconSize(QtCore.QSize(30, 30))
        self.button_pwReVisibility.setFlat(True)
        self.button_pwReVisibility.setObjectName("button_pwReVisibility")

        self.retranslateUi(AccountDialog)
        QtCore.QMetaObject.connectSlotsByName(AccountDialog)
        AccountDialog.setTabOrder(self.text_accountID, self.text_passwordNew)
        AccountDialog.setTabOrder(self.text_passwordNew, self.button_pwVisibility)
        AccountDialog.setTabOrder(self.button_pwVisibility, self.text_passwordRe)
        AccountDialog.setTabOrder(self.text_passwordRe, self.button_pwReVisibility)
        AccountDialog.setTabOrder(self.button_pwReVisibility, self.button_save)

    def retranslateUi(self, AccountDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountDialog.setWindowTitle(_translate("AccountDialog", "ACCOUNT"))
        self.label_accountInfo.setText(_translate("AccountDialog", "Thông tin tài khoản"))
        self.label_accountID.setText(_translate("AccountDialog", "ID:"))
        self.label_passwordNew.setText(_translate("AccountDialog", "Mật khẩu mới:"))
        self.button_save.setText(_translate("AccountDialog", "Lưu"))
        self.label_passwordRe.setText(_translate("AccountDialog", "Nhập lại mật khẩu:"))
import resources_rc
