# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\account_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountManagerDialog(object):
    def setupUi(self, AccountManagerDialog):
        AccountManagerDialog.setObjectName("AccountManagerDialog")
        AccountManagerDialog.resize(360, 310)
        font = QtGui.QFont()
        font.setPointSize(11)
        AccountManagerDialog.setFont(font)
        self.label_accountManager = QtWidgets.QLabel(AccountManagerDialog)
        self.label_accountManager.setGeometry(QtCore.QRect(0, 50, 360, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accountManager.setFont(font)
        self.label_accountManager.setText("")
        self.label_accountManager.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accountManager.setObjectName("label_accountManager")
        self.label_accountID = QtWidgets.QLabel(AccountManagerDialog)
        self.label_accountID.setGeometry(QtCore.QRect(30, 150, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_accountID.setFont(font)
        self.label_accountID.setObjectName("label_accountID")
        self.text_accountID = QtWidgets.QLineEdit(AccountManagerDialog)
        self.text_accountID.setEnabled(True)
        self.text_accountID.setGeometry(QtCore.QRect(130, 150, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_accountID.setFont(font)
        self.text_accountID.setText("")
        self.text_accountID.setCursorPosition(0)
        self.text_accountID.setAlignment(QtCore.Qt.AlignCenter)
        self.text_accountID.setReadOnly(True)
        self.text_accountID.setObjectName("text_accountID")
        self.label_name = QtWidgets.QLabel(AccountManagerDialog)
        self.label_name.setGeometry(QtCore.QRect(30, 190, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.button_save = QtWidgets.QPushButton(AccountManagerDialog)
        self.button_save.setGeometry(QtCore.QRect(50, 240, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setStyleSheet("#button_save{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_save:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_save:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_save:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_save.setObjectName("button_save")
        self.text_name = QtWidgets.QLineEdit(AccountManagerDialog)
        self.text_name.setGeometry(QtCore.QRect(130, 190, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_name.setFont(font)
        self.text_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.text_name.setText("")
        self.text_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.text_name.setCursorPosition(0)
        self.text_name.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_name.setObjectName("text_name")
        self.list_accounts = QtWidgets.QComboBox(AccountManagerDialog)
        self.list_accounts.setGeometry(QtCore.QRect(30, 100, 160, 30))
        self.list_accounts.setStyleSheet("border: 1px solid rgb(150, 150, 150);")
        self.list_accounts.setMaxVisibleItems(5)
        self.list_accounts.setObjectName("list_accounts")
        self.button_delete = QtWidgets.QPushButton(AccountManagerDialog)
        self.button_delete.setGeometry(QtCore.QRect(190, 240, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_delete.setFont(font)
        self.button_delete.setStyleSheet("#button_delete{\n"
"    color: rgb(240, 68, 56);\n"
"    border: 2px solid rgb(240, 68, 56);\n"
"/*\n"
"    background-color: rgb(240, 68, 56);\n"
"*/\n"
"}\n"
"#button_delete:hover{\n"
"    border-width: 4px;\n"
"/*    \n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(255, 69, 59);\n"
"*/\n"
"}\n"
"#button_delete:pressed{\n"
"    color: rgb(211, 57, 49);\n"
"    border-width: 4px;\n"
"    border-color: rgb(211, 57, 49);\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(211, 57, 49);\n"
"*/\n"
" }\n"
"#button_delete:disabled{\n"
"color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_delete.setObjectName("button_delete")
        self.button_add = QtWidgets.QPushButton(AccountManagerDialog)
        self.button_add.setGeometry(QtCore.QRect(210, 100, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_add.setFont(font)
        self.button_add.setStyleSheet("border-radius: 10px;")
        self.button_add.setObjectName("button_add")
        self.label_accountManagerTitle = QtWidgets.QLabel(AccountManagerDialog)
        self.label_accountManagerTitle.setGeometry(QtCore.QRect(0, 10, 360, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accountManagerTitle.setFont(font)
        self.label_accountManagerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accountManagerTitle.setObjectName("label_accountManagerTitle")

        self.retranslateUi(AccountManagerDialog)
        QtCore.QMetaObject.connectSlotsByName(AccountManagerDialog)
        AccountManagerDialog.setTabOrder(self.list_accounts, self.button_add)
        AccountManagerDialog.setTabOrder(self.button_add, self.text_accountID)
        AccountManagerDialog.setTabOrder(self.text_accountID, self.text_name)
        AccountManagerDialog.setTabOrder(self.text_name, self.button_save)
        AccountManagerDialog.setTabOrder(self.button_save, self.button_delete)

    def retranslateUi(self, AccountManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountManagerDialog.setWindowTitle(_translate("AccountManagerDialog", "ACCOUNT MANAGER"))
        self.label_accountID.setText(_translate("AccountManagerDialog", "ID:"))
        self.label_name.setText(_translate("AccountManagerDialog", "Họ và tên:"))
        self.button_save.setText(_translate("AccountManagerDialog", "Lưu"))
        self.button_delete.setText(_translate("AccountManagerDialog", "Xóa"))
        self.button_add.setText(_translate("AccountManagerDialog", "Thêm"))
        self.label_accountManagerTitle.setText(_translate("AccountManagerDialog", "Quản lý tài khoản"))
