# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dev.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevScreen(object):
    def setupUi(self, DevScreen):
        DevScreen.setObjectName("DevScreen")
        DevScreen.resize(1280, 740)
        DevScreen.setStyleSheet("#DevScreen{\n"
"/*\n"
"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0, stop:0.5 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"*/\n"
"\n"
"    background-color: rgb(250, 250, 250);\n"
"\n"
"}\n"
"/*#DevScreen{\n"
"    background-image: url(:/icons/icons/Logo.png);\n"
"        background-repeat: no-repeat; \n"
"        background-position: center;\n"
"    }*/\n"
"\n"
"#DevScreen QPushButton {\n"
"color: rgb(110, 143, 158);\n"
"border-radius: 20px;\n"
"border: 2px solid rgb(110, 143, 158);\n"
"/*background-color: rgb(110, 143, 158);*/\n"
"/*padding: 1px 2px;*/\n"
"font: bold 11pt \"MS Shell Dlg 2\";\n"
"}\n"
"#DevScreen QPushButton:hover{\n"
"    border-width: 4px;\n"
"    /*border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(144, 164, 175);*/\n"
"}\n"
"#DevScreen QPushButton:pressed{\n"
"    color: rgb(37, 50, 56);\n"
"    border-width: 4px;\n"
"    border-color: rgb(37, 50, 56);\n"
"    /*border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(69, 91, 102);*/\n"
" }\n"
"#DevScreen QPushButton:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"    /*color: rgb(150, 150, 150);\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"    background-color: rgb(240, 240, 240);*/\n"
"\n"
"}\n"
"\n"
"#DevScreen QDateEdit:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#DevScreen QLineEdit {\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 1px 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(DevScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_logout.setGeometry(QtCore.QRect(1150, 10, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_logout.setFont(font)
        self.button_logout.setAutoFillBackground(False)
        self.button_logout.setObjectName("button_logout")
        self.button_account = QtWidgets.QPushButton(self.centralwidget)
        self.button_account.setEnabled(True)
        self.button_account.setGeometry(QtCore.QRect(1020, 10, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_account.setFont(font)
        self.button_account.setObjectName("button_account")
        self.frame_control = QtWidgets.QFrame(self.centralwidget)
        self.frame_control.setEnabled(True)
        self.frame_control.setGeometry(QtCore.QRect(430, 80, 840, 650))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_control.setFont(font)
        self.frame_control.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control.setObjectName("frame_control")
        self.frame_exercises = QtWidgets.QFrame(self.frame_control)
        self.frame_exercises.setEnabled(False)
        self.frame_exercises.setGeometry(QtCore.QRect(0, 45, 560, 605))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frame_exercises.setFont(font)
        self.frame_exercises.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_exercises.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_exercises.setObjectName("frame_exercises")
        self.button_setHip = QtWidgets.QPushButton(self.frame_exercises)
        self.button_setHip.setGeometry(QtCore.QRect(50, 80, 120, 120))
        self.button_setHip.setMinimumSize(QtCore.QSize(120, 120))
        self.button_setHip.setStyleSheet("#button_setHip{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_setHip:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_setHip:pressed{\n"
"    background-color: rgb(235, 235, 235);\n"
" }\n"
"#button_setHip:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_setHip.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/angle_hip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_setHip.setIcon(icon)
        self.button_setHip.setIconSize(QtCore.QSize(110, 110))
        self.button_setHip.setDefault(False)
        self.button_setHip.setObjectName("button_setHip")
        self.button_setKnee = QtWidgets.QPushButton(self.frame_exercises)
        self.button_setKnee.setGeometry(QtCore.QRect(220, 80, 120, 120))
        self.button_setKnee.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setKnee.setFont(font)
        self.button_setKnee.setStyleSheet("#button_setKnee{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_setKnee:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_setKnee:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_setKnee:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_setKnee.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/angle_knee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_setKnee.setIcon(icon1)
        self.button_setKnee.setIconSize(QtCore.QSize(110, 110))
        self.button_setKnee.setObjectName("button_setKnee")
        self.button_setAnkle = QtWidgets.QPushButton(self.frame_exercises)
        self.button_setAnkle.setGeometry(QtCore.QRect(390, 80, 120, 120))
        self.button_setAnkle.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setAnkle.setFont(font)
        self.button_setAnkle.setStyleSheet("#button_setAnkle{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_setAnkle:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_setAnkle:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_setAnkle:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_setAnkle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/angle_ankle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_setAnkle.setIcon(icon2)
        self.button_setAnkle.setIconSize(QtCore.QSize(110, 110))
        self.button_setAnkle.setObjectName("button_setAnkle")
        self.button_sineKnee = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineKnee.setGeometry(QtCore.QRect(220, 260, 120, 120))
        self.button_sineKnee.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineKnee.setFont(font)
        self.button_sineKnee.setStyleSheet("#button_sineKnee{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineKnee:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineKnee:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineKnee:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineKnee.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/sine_knee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineKnee.setIcon(icon3)
        self.button_sineKnee.setIconSize(QtCore.QSize(110, 110))
        self.button_sineKnee.setObjectName("button_sineKnee")
        self.button_sineHip = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineHip.setGeometry(QtCore.QRect(50, 260, 120, 120))
        self.button_sineHip.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineHip.setFont(font)
        self.button_sineHip.setStyleSheet("#button_sineHip{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineHip:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineHip:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineHip:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineHip.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/sine_hip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineHip.setIcon(icon4)
        self.button_sineHip.setIconSize(QtCore.QSize(110, 110))
        self.button_sineHip.setObjectName("button_sineHip")
        self.button_sineAnkle = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineAnkle.setGeometry(QtCore.QRect(390, 260, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sineAnkle.sizePolicy().hasHeightForWidth())
        self.button_sineAnkle.setSizePolicy(sizePolicy)
        self.button_sineAnkle.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineAnkle.setFont(font)
        self.button_sineAnkle.setStyleSheet("#button_sineAnkle{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineAnkle:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineAnkle:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineAnkle:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineAnkle.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/sine_ankle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineAnkle.setIcon(icon5)
        self.button_sineAnkle.setIconSize(QtCore.QSize(110, 110))
        self.button_sineAnkle.setObjectName("button_sineAnkle")
        self.button_bikeEx = QtWidgets.QPushButton(self.frame_exercises)
        self.button_bikeEx.setGeometry(QtCore.QRect(220, 440, 120, 120))
        self.button_bikeEx.setMinimumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_bikeEx.setFont(font)
        self.button_bikeEx.setStyleSheet("#button_bikeEx{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_bikeEx:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_bikeEx:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_bikeEx:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_bikeEx.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/bike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bikeEx.setIcon(icon6)
        self.button_bikeEx.setIconSize(QtCore.QSize(110, 110))
        self.button_bikeEx.setObjectName("button_bikeEx")
        self.label_exercisesSelect = QtWidgets.QLabel(self.frame_exercises)
        self.label_exercisesSelect.setGeometry(QtCore.QRect(50, 0, 460, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_exercisesSelect.setFont(font)
        self.label_exercisesSelect.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_exercisesSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_exercisesSelect.setLineWidth(1)
        self.label_exercisesSelect.setTextFormat(QtCore.Qt.AutoText)
        self.label_exercisesSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exercisesSelect.setObjectName("label_exercisesSelect")
        self.button_setAnkle.raise_()
        self.button_sineAnkle.raise_()
        self.button_sineHip.raise_()
        self.button_setHip.raise_()
        self.button_bikeEx.raise_()
        self.button_setKnee.raise_()
        self.button_sineKnee.raise_()
        self.label_exercisesSelect.raise_()
        self.frame_set = QtWidgets.QFrame(self.frame_control)
        self.frame_set.setEnabled(True)
        self.frame_set.setGeometry(QtCore.QRect(560, 200, 280, 450))
        self.frame_set.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_set.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_set.setObjectName("frame_set")
        self.button_start = QtWidgets.QPushButton(self.frame_set)
        self.button_start.setEnabled(False)
        self.button_start.setGeometry(QtCore.QRect(0, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("#button_start{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(21, 115, 71);\n"
"}\n"
"#button_start:hover{\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"#button_start:pressed{\n"
"    background-color: rgb(0, 107, 0);\n"
" }\n"
"#button_start:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(self.frame_set)
        self.button_stop.setEnabled(False)
        self.button_stop.setGeometry(QtCore.QRect(160, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_stop.setFont(font)
        self.button_stop.setAutoFillBackground(False)
        self.button_stop.setStyleSheet("#button_stop{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(187, 43, 59);\n"
"}\n"
"#button_stop:hover{\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"#button_stop:pressed{\n"
"    background-color: rgb(150, 0, 0);\n"
" }\n"
"#button_stop:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_stop.setObjectName("button_stop")
        self.button_confirm = QtWidgets.QPushButton(self.frame_set)
        self.button_confirm.setEnabled(False)
        self.button_confirm.setGeometry(QtCore.QRect(80, 250, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_confirm.setFont(font)
        self.button_confirm.setStyleSheet("#button_confirm{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(248, 152, 29);\n"
"}\n"
"#button_confirm:hover{\n"
"    background-color: rgb(255, 154, 30);\n"
"}\n"
"#button_confirm:pressed{\n"
"    background-color: rgb(255, 150, 0);\n"
" }\n"
"#button_confirm:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_confirm.setObjectName("button_confirm")
        self.button_setCycles = QtWidgets.QPushButton(self.frame_set)
        self.button_setCycles.setEnabled(False)
        self.button_setCycles.setGeometry(QtCore.QRect(0, 40, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setCycles.setFont(font)
        self.button_setCycles.setObjectName("button_setCycles")
        self.button_setTimer = QtWidgets.QPushButton(self.frame_set)
        self.button_setTimer.setEnabled(False)
        self.button_setTimer.setGeometry(QtCore.QRect(160, 40, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setTimer.setFont(font)
        self.button_setTimer.setAutoFillBackground(False)
        self.button_setTimer.setObjectName("button_setTimer")
        self.text_cycles = QtWidgets.QLineEdit(self.frame_set)
        self.text_cycles.setEnabled(False)
        self.text_cycles.setGeometry(QtCore.QRect(0, 0, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_cycles.setFont(font)
        self.text_cycles.setInputMask("")
        self.text_cycles.setAlignment(QtCore.Qt.AlignCenter)
        self.text_cycles.setClearButtonEnabled(False)
        self.text_cycles.setObjectName("text_cycles")
        self.text_timer = QtWidgets.QTimeEdit(self.frame_set)
        self.text_timer.setEnabled(False)
        self.text_timer.setGeometry(QtCore.QRect(160, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_timer.setFont(font)
        self.text_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.text_timer.setObjectName("text_timer")
        self.label_cycles = QtWidgets.QLabel(self.frame_set)
        self.label_cycles.setEnabled(False)
        self.label_cycles.setGeometry(QtCore.QRect(66, 0, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cycles.setFont(font)
        self.label_cycles.setObjectName("label_cycles")
        self.label_timer = QtWidgets.QLabel(self.frame_set)
        self.label_timer.setEnabled(False)
        self.label_timer.setGeometry(QtCore.QRect(250, 0, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_timer.setFont(font)
        self.label_timer.setObjectName("label_timer")
        self.label_exercise = QtWidgets.QLabel(self.frame_set)
        self.label_exercise.setGeometry(QtCore.QRect(0, 120, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_exercise.setFont(font)
        self.label_exercise.setText("")
        self.label_exercise.setObjectName("label_exercise")
        self.text_exercise = QtWidgets.QLabel(self.frame_set)
        self.text_exercise.setGeometry(QtCore.QRect(100, 120, 180, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_exercise.setFont(font)
        self.text_exercise.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_exercise.setText("")
        self.text_exercise.setAlignment(QtCore.Qt.AlignCenter)
        self.text_exercise.setWordWrap(True)
        self.text_exercise.setObjectName("text_exercise")
        self.text_cycles_timer = QtWidgets.QLabel(self.frame_set)
        self.text_cycles_timer.setGeometry(QtCore.QRect(100, 210, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_cycles_timer.setFont(font)
        self.text_cycles_timer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_cycles_timer.setText("")
        self.text_cycles_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.text_cycles_timer.setObjectName("text_cycles_timer")
        self.label_cycles_timer = QtWidgets.QLabel(self.frame_set)
        self.label_cycles_timer.setGeometry(QtCore.QRect(0, 210, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cycles_timer.setFont(font)
        self.label_cycles_timer.setText("")
        self.label_cycles_timer.setObjectName("label_cycles_timer")
        self.frame_session = QtWidgets.QFrame(self.frame_control)
        self.frame_session.setEnabled(True)
        self.frame_session.setGeometry(QtCore.QRect(560, 45, 280, 140))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_session.setFont(font)
        self.frame_session.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_session.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_session.setObjectName("frame_session")
        self.button_sessionCreate = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionCreate.setGeometry(QtCore.QRect(0, 80, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionCreate.setFont(font)
        self.button_sessionCreate.setStyleSheet("#button_sessionCreate{\n"
"    color: rgb(43, 116, 185);\n"
"    border: 2px solid rgb(43, 116, 185);\n"
"/*\n"
"    background-color: rgb(43, 116, 185);\n"
"*/\n"
"}\n"
"#button_sessionCreate:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(52, 141, 225);\n"
"*/\n"
"}\n"
"#button_sessionCreate:pressed{\n"
"    color: rgb(37, 99, 158);\n"
"    border-width: 4px;\n"
"    border-color: rgb(37, 99, 158);\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(37, 99, 158);\n"
"*/\n"
" }\n"
"#button_sessionCreate:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_sessionCreate.setObjectName("button_sessionCreate")
        self.text_sessionTitle = QtWidgets.QLineEdit(self.frame_session)
        self.text_sessionTitle.setGeometry(QtCore.QRect(0, 40, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_sessionTitle.setFont(font)
        self.text_sessionTitle.setClearButtonEnabled(True)
        self.text_sessionTitle.setObjectName("text_sessionTitle")
        self.button_sessionSave = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionSave.setEnabled(False)
        self.button_sessionSave.setGeometry(QtCore.QRect(160, 80, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionSave.setFont(font)
        self.button_sessionSave.setStyleSheet("#button_sessionSave{\n"
"    color: rgb(184, 168, 20);\n"
"    border: 2px solid rgb(184, 168, 20);\n"
"/*\n"
"    background-color: rgb(184, 168, 20);\n"
"*/\n"
"}\n"
"#button_sessionSave:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(230, 210, 25);\n"
"*/\n"
"}\n"
"#button_sessionSave:pressed{\n"
"    color: rgb(150, 137, 16);\n"
"    border-width: 4px;\n"
"    border-color: rgb(150, 137, 16);\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(150, 137, 16);\n"
"*/\n"
" }\n"
"#button_sessionSave:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_sessionSave.setObjectName("button_sessionSave")
        self.label_frameSession = QtWidgets.QLabel(self.frame_session)
        self.label_frameSession.setEnabled(True)
        self.label_frameSession.setGeometry(QtCore.QRect(0, 0, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_frameSession.setFont(font)
        self.label_frameSession.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_frameSession.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_frameSession.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frameSession.setObjectName("label_frameSession")
        self.button_sessionEdit = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionEdit.setEnabled(False)
        self.button_sessionEdit.setGeometry(QtCore.QRect(220, 40, 60, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionEdit.setFont(font)
        self.button_sessionEdit.setStyleSheet("border-radius: 10px;\n"
"")
        self.button_sessionEdit.setObjectName("button_sessionEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 80, 420, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_unitHeight = QtWidgets.QLabel(self.frame)
        self.label_unitHeight.setGeometry(QtCore.QRect(395, 105, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitHeight.setFont(font)
        self.label_unitHeight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitHeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitHeight.setLineWidth(1)
        self.label_unitHeight.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitHeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitHeight.setObjectName("label_unitHeight")
        self.label_weight = QtWidgets.QLabel(self.frame)
        self.label_weight.setGeometry(QtCore.QRect(0, 105, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_weight.setFont(font)
        self.label_weight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_weight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_weight.setLineWidth(1)
        self.label_weight.setTextFormat(QtCore.Qt.AutoText)
        self.label_weight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_weight.setObjectName("label_weight")
        self.label_shank = QtWidgets.QLabel(self.frame)
        self.label_shank.setGeometry(QtCore.QRect(215, 175, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_shank.setFont(font)
        self.label_shank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_shank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_shank.setLineWidth(1)
        self.label_shank.setTextFormat(QtCore.Qt.AutoText)
        self.label_shank.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_shank.setObjectName("label_shank")
        self.text_weight = QtWidgets.QLineEdit(self.frame)
        self.text_weight.setEnabled(False)
        self.text_weight.setGeometry(QtCore.QRect(90, 105, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_weight.setFont(font)
        self.text_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.text_weight.setClearButtonEnabled(False)
        self.text_weight.setObjectName("text_weight")
        self.label_height = QtWidgets.QLabel(self.frame)
        self.label_height.setGeometry(QtCore.QRect(220, 105, 85, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_height.setFont(font)
        self.label_height.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_height.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_height.setLineWidth(1)
        self.label_height.setTextFormat(QtCore.Qt.AutoText)
        self.label_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_height.setObjectName("label_height")
        self.text_height = QtWidgets.QLineEdit(self.frame)
        self.text_height.setEnabled(False)
        self.text_height.setGeometry(QtCore.QRect(315, 105, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_height.setFont(font)
        self.text_height.setAlignment(QtCore.Qt.AlignCenter)
        self.text_height.setClearButtonEnabled(False)
        self.text_height.setObjectName("text_height")
        self.text_shank = QtWidgets.QLineEdit(self.frame)
        self.text_shank.setEnabled(False)
        self.text_shank.setGeometry(QtCore.QRect(315, 175, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_shank.setFont(font)
        self.text_shank.setAlignment(QtCore.Qt.AlignCenter)
        self.text_shank.setClearButtonEnabled(False)
        self.text_shank.setObjectName("text_shank")
        self.button_dataEdit = QtWidgets.QPushButton(self.frame)
        self.button_dataEdit.setEnabled(True)
        self.button_dataEdit.setGeometry(QtCore.QRect(60, 370, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_dataEdit.setFont(font)
        self.button_dataEdit.setObjectName("button_dataEdit")
        self.label_leg = QtWidgets.QLabel(self.frame)
        self.label_leg.setGeometry(QtCore.QRect(0, 140, 135, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_leg.setFont(font)
        self.label_leg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_leg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_leg.setLineWidth(1)
        self.label_leg.setTextFormat(QtCore.Qt.AutoText)
        self.label_leg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_leg.setObjectName("label_leg")
        self.label_unitShank = QtWidgets.QLabel(self.frame)
        self.label_unitShank.setGeometry(QtCore.QRect(395, 175, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitShank.setFont(font)
        self.label_unitShank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitShank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitShank.setLineWidth(1)
        self.label_unitShank.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitShank.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitShank.setObjectName("label_unitShank")
        self.button_dataSave = QtWidgets.QPushButton(self.frame)
        self.button_dataSave.setEnabled(False)
        self.button_dataSave.setGeometry(QtCore.QRect(240, 370, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_dataSave.setFont(font)
        self.button_dataSave.setStyleSheet("#button_dataSave{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_dataSave:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_dataSave:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_dataSave:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_dataSave.setObjectName("button_dataSave")
        self.label_controlData = QtWidgets.QLabel(self.frame)
        self.label_controlData.setGeometry(QtCore.QRect(0, 45, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_controlData.setFont(font)
        self.label_controlData.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_controlData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_controlData.setLineWidth(1)
        self.label_controlData.setTextFormat(QtCore.Qt.AutoText)
        self.label_controlData.setAlignment(QtCore.Qt.AlignCenter)
        self.label_controlData.setObjectName("label_controlData")
        self.text_thigh = QtWidgets.QLineEdit(self.frame)
        self.text_thigh.setEnabled(False)
        self.text_thigh.setGeometry(QtCore.QRect(45, 175, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_thigh.setFont(font)
        self.text_thigh.setAlignment(QtCore.Qt.AlignCenter)
        self.text_thigh.setClearButtonEnabled(False)
        self.text_thigh.setObjectName("text_thigh")
        self.label_unitThigh = QtWidgets.QLabel(self.frame)
        self.label_unitThigh.setGeometry(QtCore.QRect(125, 175, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitThigh.setFont(font)
        self.label_unitThigh.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitThigh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitThigh.setLineWidth(1)
        self.label_unitThigh.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitThigh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitThigh.setObjectName("label_unitThigh")
        self.label_unitWeight = QtWidgets.QLabel(self.frame)
        self.label_unitWeight.setGeometry(QtCore.QRect(170, 105, 20, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitWeight.setFont(font)
        self.label_unitWeight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitWeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitWeight.setLineWidth(1)
        self.label_unitWeight.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitWeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitWeight.setObjectName("label_unitWeight")
        self.label_thigh = QtWidgets.QLabel(self.frame)
        self.label_thigh.setGeometry(QtCore.QRect(0, 175, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_thigh.setFont(font)
        self.label_thigh.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_thigh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_thigh.setLineWidth(1)
        self.label_thigh.setTextFormat(QtCore.Qt.AutoText)
        self.label_thigh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_thigh.setObjectName("label_thigh")
        self.label_controlCoef = QtWidgets.QLabel(self.frame)
        self.label_controlCoef.setGeometry(QtCore.QRect(0, 250, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_controlCoef.setFont(font)
        self.label_controlCoef.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_controlCoef.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_controlCoef.setLineWidth(1)
        self.label_controlCoef.setTextFormat(QtCore.Qt.AutoText)
        self.label_controlCoef.setAlignment(QtCore.Qt.AlignCenter)
        self.label_controlCoef.setObjectName("label_controlCoef")
        self.text_coefP = QtWidgets.QLineEdit(self.frame)
        self.text_coefP.setEnabled(False)
        self.text_coefP.setGeometry(QtCore.QRect(30, 315, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_coefP.setFont(font)
        self.text_coefP.setAlignment(QtCore.Qt.AlignCenter)
        self.text_coefP.setClearButtonEnabled(False)
        self.text_coefP.setObjectName("text_coefP")
        self.label_coefP = QtWidgets.QLabel(self.frame)
        self.label_coefP.setGeometry(QtCore.QRect(0, 315, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_coefP.setFont(font)
        self.label_coefP.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_coefP.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_coefP.setLineWidth(1)
        self.label_coefP.setTextFormat(QtCore.Qt.AutoText)
        self.label_coefP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_coefP.setObjectName("label_coefP")
        self.text_coefI = QtWidgets.QLineEdit(self.frame)
        self.text_coefI.setEnabled(False)
        self.text_coefI.setGeometry(QtCore.QRect(180, 315, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_coefI.setFont(font)
        self.text_coefI.setAlignment(QtCore.Qt.AlignCenter)
        self.text_coefI.setClearButtonEnabled(False)
        self.text_coefI.setObjectName("text_coefI")
        self.label_coefI = QtWidgets.QLabel(self.frame)
        self.label_coefI.setGeometry(QtCore.QRect(150, 315, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_coefI.setFont(font)
        self.label_coefI.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_coefI.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_coefI.setLineWidth(1)
        self.label_coefI.setTextFormat(QtCore.Qt.AutoText)
        self.label_coefI.setAlignment(QtCore.Qt.AlignCenter)
        self.label_coefI.setObjectName("label_coefI")
        self.text_coefD = QtWidgets.QLineEdit(self.frame)
        self.text_coefD.setEnabled(False)
        self.text_coefD.setGeometry(QtCore.QRect(330, 315, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_coefD.setFont(font)
        self.text_coefD.setAlignment(QtCore.Qt.AlignCenter)
        self.text_coefD.setClearButtonEnabled(False)
        self.text_coefD.setObjectName("text_coefD")
        self.label_coefD = QtWidgets.QLabel(self.frame)
        self.label_coefD.setGeometry(QtCore.QRect(300, 315, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_coefD.setFont(font)
        self.label_coefD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_coefD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_coefD.setLineWidth(1)
        self.label_coefD.setTextFormat(QtCore.Qt.AutoText)
        self.label_coefD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_coefD.setObjectName("label_coefD")
        self.label_accAdd = QtWidgets.QLabel(self.frame)
        self.label_accAdd.setGeometry(QtCore.QRect(0, 470, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accAdd.setFont(font)
        self.label_accAdd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_accAdd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_accAdd.setLineWidth(1)
        self.label_accAdd.setTextFormat(QtCore.Qt.AutoText)
        self.label_accAdd.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accAdd.setObjectName("label_accAdd")
        self.button_accDev = QtWidgets.QPushButton(self.frame)
        self.button_accDev.setEnabled(True)
        self.button_accDev.setGeometry(QtCore.QRect(240, 545, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_accDev.setFont(font)
        self.button_accDev.setObjectName("button_accDev")
        self.button_accDoctor = QtWidgets.QPushButton(self.frame)
        self.button_accDoctor.setEnabled(True)
        self.button_accDoctor.setGeometry(QtCore.QRect(60, 545, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_accDoctor.setFont(font)
        self.button_accDoctor.setObjectName("button_accDoctor")
        self.label_dispID = QtWidgets.QLabel(self.frame)
        self.label_dispID.setEnabled(False)
        self.label_dispID.setGeometry(QtCore.QRect(40, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_dispID.setFont(font)
        self.label_dispID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);\n"
"")
        self.label_dispID.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_dispID.setText("")
        self.label_dispID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dispID.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_dispID.setObjectName("label_dispID")
        self.label_ID = QtWidgets.QLabel(self.frame)
        self.label_ID.setGeometry(QtCore.QRect(0, 0, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_ID.setFont(font)
        self.label_ID.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_ID.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_ID.setLineWidth(1)
        self.label_ID.setTextFormat(QtCore.Qt.AutoText)
        self.label_ID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ID.setObjectName("label_ID")
        self.label_HUST = QtWidgets.QLabel(self.centralwidget)
        self.label_HUST.setGeometry(QtCore.QRect(10, 10, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_HUST.setFont(font)
        self.label_HUST.setStyleSheet("image: url(:/icons/icons/HUST.png);")
        self.label_HUST.setText("")
        self.label_HUST.setObjectName("label_HUST")
        self.label_Komlab = QtWidgets.QLabel(self.centralwidget)
        self.label_Komlab.setGeometry(QtCore.QRect(70, 10, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Komlab.setFont(font)
        self.label_Komlab.setStyleSheet("image: url(:/icons/icons/KomLab.png);")
        self.label_Komlab.setText("")
        self.label_Komlab.setObjectName("label_Komlab")
        self.frame_control.raise_()
        self.button_account.raise_()
        self.button_logout.raise_()
        self.frame.raise_()
        self.label_HUST.raise_()
        self.label_Komlab.raise_()
        DevScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(DevScreen)
        self.button_sineHip.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_sineAnkle.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_sineKnee.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_setHip.clicked['bool'].connect(self.button_setCycles.setEnabled) # type: ignore
        self.button_setKnee.clicked['bool'].connect(self.button_setCycles.setEnabled) # type: ignore
        self.button_setHip.clicked['bool'].connect(self.button_setTimer.setEnabled) # type: ignore
        self.button_setKnee.clicked['bool'].connect(self.button_setTimer.setEnabled) # type: ignore
        self.button_setAnkle.clicked['bool'].connect(self.button_setCycles.setEnabled) # type: ignore
        self.button_setAnkle.clicked['bool'].connect(self.button_setTimer.setEnabled) # type: ignore
        self.text_cycles.returnPressed.connect(self.button_setCycles.setFocus) # type: ignore
        self.text_timer.editingFinished.connect(self.button_setTimer.setFocus) # type: ignore
        self.button_bikeEx.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DevScreen)
        DevScreen.setTabOrder(self.text_weight, self.text_height)
        DevScreen.setTabOrder(self.text_height, self.text_thigh)
        DevScreen.setTabOrder(self.text_thigh, self.text_shank)
        DevScreen.setTabOrder(self.text_shank, self.text_coefP)
        DevScreen.setTabOrder(self.text_coefP, self.text_coefI)
        DevScreen.setTabOrder(self.text_coefI, self.text_coefD)
        DevScreen.setTabOrder(self.text_coefD, self.button_dataEdit)
        DevScreen.setTabOrder(self.button_dataEdit, self.button_dataSave)
        DevScreen.setTabOrder(self.button_dataSave, self.button_accDoctor)
        DevScreen.setTabOrder(self.button_accDoctor, self.button_accDev)
        DevScreen.setTabOrder(self.button_accDev, self.text_sessionTitle)
        DevScreen.setTabOrder(self.text_sessionTitle, self.button_sessionCreate)
        DevScreen.setTabOrder(self.button_sessionCreate, self.button_sessionEdit)
        DevScreen.setTabOrder(self.button_sessionEdit, self.button_sessionSave)
        DevScreen.setTabOrder(self.button_sessionSave, self.button_setHip)
        DevScreen.setTabOrder(self.button_setHip, self.button_setKnee)
        DevScreen.setTabOrder(self.button_setKnee, self.button_setAnkle)
        DevScreen.setTabOrder(self.button_setAnkle, self.button_sineHip)
        DevScreen.setTabOrder(self.button_sineHip, self.button_sineKnee)
        DevScreen.setTabOrder(self.button_sineKnee, self.button_sineAnkle)
        DevScreen.setTabOrder(self.button_sineAnkle, self.button_bikeEx)
        DevScreen.setTabOrder(self.button_bikeEx, self.text_cycles)
        DevScreen.setTabOrder(self.text_cycles, self.button_setCycles)
        DevScreen.setTabOrder(self.button_setCycles, self.text_timer)
        DevScreen.setTabOrder(self.text_timer, self.button_setTimer)
        DevScreen.setTabOrder(self.button_setTimer, self.button_confirm)
        DevScreen.setTabOrder(self.button_confirm, self.button_start)
        DevScreen.setTabOrder(self.button_start, self.button_stop)
        DevScreen.setTabOrder(self.button_stop, self.button_account)
        DevScreen.setTabOrder(self.button_account, self.button_logout)

    def retranslateUi(self, DevScreen):
        _translate = QtCore.QCoreApplication.translate
        DevScreen.setWindowTitle(_translate("DevScreen", "LLR_APP"))
        self.button_logout.setText(_translate("DevScreen", "Đăng xuất"))
        self.button_account.setText(_translate("DevScreen", "Tài khoản"))
        self.label_exercisesSelect.setText(_translate("DevScreen", "Lựa chọn bài tập"))
        self.button_start.setText(_translate("DevScreen", "BẮT ĐẦU"))
        self.button_stop.setText(_translate("DevScreen", "DỪNG"))
        self.button_confirm.setText(_translate("DevScreen", "Xác nhận"))
        self.button_setCycles.setText(_translate("DevScreen", "Đặt số chu kỳ"))
        self.button_setTimer.setText(_translate("DevScreen", "Đặt thời gian"))
        self.text_timer.setDisplayFormat(_translate("DevScreen", "mm:ss"))
        self.label_cycles.setText(_translate("DevScreen", "chu kỳ"))
        self.label_timer.setText(_translate("DevScreen", "m:s"))
        self.button_sessionCreate.setText(_translate("DevScreen", "Tạo buổi tập"))
        self.button_sessionSave.setText(_translate("DevScreen", "Lưu/Báo cáo"))
        self.label_frameSession.setText(_translate("DevScreen", "Buổi tập / Báo cáo"))
        self.button_sessionEdit.setText(_translate("DevScreen", "Sửa"))
        self.label_unitHeight.setText(_translate("DevScreen", "cm"))
        self.label_weight.setText(_translate("DevScreen", "Cân nặng:"))
        self.label_shank.setText(_translate("DevScreen", "Cẳng chân:"))
        self.label_height.setText(_translate("DevScreen", "Chiều cao:"))
        self.button_dataEdit.setText(_translate("DevScreen", "Sửa"))
        self.label_leg.setText(_translate("DevScreen", "Kích thước chân:"))
        self.label_unitShank.setText(_translate("DevScreen", "cm"))
        self.button_dataSave.setText(_translate("DevScreen", "Lưu"))
        self.label_controlData.setText(_translate("DevScreen", "Thông số điều khiển"))
        self.label_unitThigh.setText(_translate("DevScreen", "cm"))
        self.label_unitWeight.setText(_translate("DevScreen", "Kg"))
        self.label_thigh.setText(_translate("DevScreen", "Đùi:"))
        self.label_controlCoef.setText(_translate("DevScreen", "Hệ số điều khiển"))
        self.label_coefP.setText(_translate("DevScreen", "P:"))
        self.label_coefI.setText(_translate("DevScreen", "I:"))
        self.label_coefD.setText(_translate("DevScreen", "D:"))
        self.label_accAdd.setText(_translate("DevScreen", "Quản lý tài khoản"))
        self.button_accDev.setText(_translate("DevScreen", "Kỹ thuật viên"))
        self.button_accDoctor.setText(_translate("DevScreen", "Bác sỹ"))
        self.label_ID.setText(_translate("DevScreen", "ID:"))
import resources_rc
