# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(1280, 740)
        font = QtGui.QFont()
        font.setPointSize(11)
        LoginScreen.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/KomLab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginScreen.setWindowIcon(icon)
        LoginScreen.setStyleSheet("QDialog{\n"
"/*    \n"
"    background-image: url(:/icons/icons/KomLab.png); \n"
"    background-repeat: no-repeat; \n"
"    background-position: top;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0, stop:0.5 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"*/\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"#LoginScreen QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(71, 142, 204);\n"
"}\n"
"#LoginScreen QPushButton:hover{\n"
"    background-color: rgb(112, 178, 226);\n"
"}\n"
"#LoginScreen QPushButton:pressed{\n"
"    background-color: rgb(43, 116, 185);\n"
" }\n"
"#LoginScreen QPushButton:disabled{\n"
"    background-color: rgb(190, 222, 245);\n"
"}\n"
"\n"
"#LoginScreen QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"    padding: 1px 2px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        LoginScreen.setSizeGripEnabled(False)
        self.frame = QtWidgets.QFrame(LoginScreen)
        self.frame.setGeometry(QtCore.QRect(410, 280, 460, 260))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_password = QtWidgets.QLabel(self.frame)
        self.label_password.setGeometry(QtCore.QRect(120, 70, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.labe_ID = QtWidgets.QLabel(self.frame)
        self.labe_ID.setGeometry(QtCore.QRect(120, 0, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labe_ID.setFont(font)
        self.labe_ID.setObjectName("labe_ID")
        self.text_inputPassword = QtWidgets.QLineEdit(self.frame)
        self.text_inputPassword.setGeometry(QtCore.QRect(120, 100, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_inputPassword.setFont(font)
        self.text_inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_inputPassword.setObjectName("text_inputPassword")
        self.button_login = QtWidgets.QPushButton(self.frame)
        self.button_login.setGeometry(QtCore.QRect(170, 200, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_login.setFont(font)
        self.button_login.setObjectName("button_login")
        self.text_inputID = QtWidgets.QLineEdit(self.frame)
        self.text_inputID.setGeometry(QtCore.QRect(120, 30, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_inputID.setFont(font)
        self.text_inputID.setAlignment(QtCore.Qt.AlignCenter)
        self.text_inputID.setObjectName("text_inputID")
        self.button_visibility = QtWidgets.QPushButton(self.frame)
        self.button_visibility.setGeometry(QtCore.QRect(350, 100, 30, 30))
        self.button_visibility.setAutoFillBackground(False)
        self.button_visibility.setStyleSheet("image: url(:/icons/icons/show.png);\n"
"color: rgb(0, 0, 0); \n"
"background-color: rgba(255, 255, 255, 0);\n"
"border:0px;")
        self.button_visibility.setText("")
        self.button_visibility.setObjectName("button_visibility")
        self.label_notification = QtWidgets.QLabel(self.frame)
        self.label_notification.setGeometry(QtCore.QRect(0, 150, 460, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_notification.setFont(font)
        self.label_notification.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_notification.setText("")
        self.label_notification.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notification.setObjectName("label_notification")
        self.label_title = QtWidgets.QLabel(LoginScreen)
        self.label_title.setGeometry(QtCore.QRect(340, 220, 600, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(0, 170, 255);\n"
"color: rgb(110, 143, 158);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_Komlab = QtWidgets.QLabel(LoginScreen)
        self.label_Komlab.setGeometry(QtCore.QRect(650, 10, 200, 200))
        self.label_Komlab.setText("")
        self.label_Komlab.setPixmap(QtGui.QPixmap(":/icons/icons/Logo.png"))
        self.label_Komlab.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Komlab.setObjectName("label_Komlab")
        self.label_HUST = QtWidgets.QLabel(LoginScreen)
        self.label_HUST.setGeometry(QtCore.QRect(450, 10, 200, 200))
        self.label_HUST.setText("")
        self.label_HUST.setTextFormat(QtCore.Qt.AutoText)
        self.label_HUST.setPixmap(QtGui.QPixmap(":/icons/icons/HUST_logo.png"))
        self.label_HUST.setScaledContents(False)
        self.label_HUST.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HUST.setObjectName("label_HUST")

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)
        LoginScreen.setTabOrder(self.text_inputID, self.text_inputPassword)
        LoginScreen.setTabOrder(self.text_inputPassword, self.button_visibility)
        LoginScreen.setTabOrder(self.button_visibility, self.button_login)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "LLR_APP"))
        self.label_password.setText(_translate("LoginScreen", "Mật khẩu"))
        self.labe_ID.setText(_translate("LoginScreen", "ID"))
        self.button_login.setText(_translate("LoginScreen", "LOGIN"))
        self.label_title.setText(_translate("LoginScreen", "LOWERLIMB REHABILITATION ROBOT"))
import resources_rc
