# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PatientScreen(object):
    def setupUi(self, PatientScreen):
        PatientScreen.setObjectName("PatientScreen")
        PatientScreen.resize(1280, 740)
        font = QtGui.QFont()
        font.setPointSize(11)
        PatientScreen.setFont(font)
        PatientScreen.setStyleSheet("#PatientScreen{\n"
"/*\n"
"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0, y2:0, stop:0.5 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"*/\n"
"\n"
"    background-color: rgb(250, 250, 250);\n"
"\n"
"}\n"
"/*#PatientScreen{\n"
"    background-image: url(:/icons/icons/Logo.png);\n"
"        background-repeat: no-repeat; \n"
"        background-position: center;\n"
"    }*/\n"
"\n"
"#PatientScreen QPushButton {\n"
"color: rgb(110, 143, 158);\n"
"border-radius: 20px;\n"
"border: 2px solid rgb(110, 143, 158);\n"
"/*background-color: rgb(110, 143, 158);*/\n"
"/*padding: 1px 2px;*/\n"
"font: bold 11pt \"MS Shell Dlg 2\";\n"
"}\n"
"#PatientScreen QPushButton:hover{\n"
"    border-width: 4px;\n"
"    /*border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(144, 164, 175);*/\n"
"}\n"
"#PatientScreen QPushButton:pressed{\n"
"    color: rgb(37, 50, 56);\n"
"    border-width: 4px;\n"
"    border-color: rgb(37, 50, 56);\n"
"    /*border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(69, 91, 102);*/\n"
" }\n"
"#PatientScreen QPushButton:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"    /*color: rgb(150, 150, 150);\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"    background-color: rgb(240, 240, 240);*/\n"
"\n"
"}\n"
"\n"
"#PatientScreen QDateEdit:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#PatientScreen QLineEdit {\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);\n"
"padding: 1px 2px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(PatientScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button_logout = QtWidgets.QPushButton(self.centralwidget)
        self.button_logout.setGeometry(QtCore.QRect(1150, 10, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_logout.setFont(font)
        self.button_logout.setAutoFillBackground(False)
        self.button_logout.setStyleSheet("")
        self.button_logout.setObjectName("button_logout")
        self.button_account = QtWidgets.QPushButton(self.centralwidget)
        self.button_account.setEnabled(True)
        self.button_account.setGeometry(QtCore.QRect(1020, 10, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_account.setFont(font)
        self.button_account.setStyleSheet("")
        self.button_account.setObjectName("button_account")
        self.frame_info = QtWidgets.QFrame(self.centralwidget)
        self.frame_info.setEnabled(True)
        self.frame_info.setGeometry(QtCore.QRect(10, 80, 420, 650))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_info.setFont(font)
        self.frame_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.button_infoSave = QtWidgets.QPushButton(self.frame_info)
        self.button_infoSave.setEnabled(False)
        self.button_infoSave.setGeometry(QtCore.QRect(240, 590, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_infoSave.setFont(font)
        self.button_infoSave.setStyleSheet("#button_infoSave{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_infoSave:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_infoSave:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_infoSave:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_infoSave.setObjectName("button_infoSave")
        self.button_infoEdit = QtWidgets.QPushButton(self.frame_info)
        self.button_infoEdit.setEnabled(False)
        self.button_infoEdit.setGeometry(QtCore.QRect(60, 590, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_infoEdit.setFont(font)
        self.button_infoEdit.setStyleSheet("")
        self.button_infoEdit.setObjectName("button_infoEdit")
        self.label_infoGeneral = QtWidgets.QLabel(self.frame_info)
        self.label_infoGeneral.setGeometry(QtCore.QRect(0, 45, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_infoGeneral.setFont(font)
        self.label_infoGeneral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_infoGeneral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_infoGeneral.setLineWidth(1)
        self.label_infoGeneral.setTextFormat(QtCore.Qt.AutoText)
        self.label_infoGeneral.setAlignment(QtCore.Qt.AlignCenter)
        self.label_infoGeneral.setObjectName("label_infoGeneral")
        self.label_ID = QtWidgets.QLabel(self.frame_info)
        self.label_ID.setGeometry(QtCore.QRect(0, 85, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_ID.setFont(font)
        self.label_ID.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_ID.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_ID.setLineWidth(1)
        self.label_ID.setTextFormat(QtCore.Qt.AutoText)
        self.label_ID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_ID.setObjectName("label_ID")
        self.text_name = QtWidgets.QLineEdit(self.frame_info)
        self.text_name.setEnabled(False)
        self.text_name.setGeometry(QtCore.QRect(225, 85, 195, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_name.setFont(font)
        self.text_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_name.setInputMask("")
        self.text_name.setText("")
        self.text_name.setMaxLength(32767)
        self.text_name.setCursorPosition(0)
        self.text_name.setAlignment(QtCore.Qt.AlignCenter)
        self.text_name.setClearButtonEnabled(False)
        self.text_name.setObjectName("text_name")
        self.label_name = QtWidgets.QLabel(self.frame_info)
        self.label_name.setGeometry(QtCore.QRect(130, 85, 85, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_name.setLineWidth(1)
        self.label_name.setTextFormat(QtCore.Qt.AutoText)
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.label_gender = QtWidgets.QLabel(self.frame_info)
        self.label_gender.setGeometry(QtCore.QRect(0, 155, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_gender.setFont(font)
        self.label_gender.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_gender.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_gender.setLineWidth(1)
        self.label_gender.setTextFormat(QtCore.Qt.AutoText)
        self.label_gender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_gender.setObjectName("label_gender")
        self.label_age = QtWidgets.QLabel(self.frame_info)
        self.label_age.setGeometry(QtCore.QRect(300, 120, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_age.setFont(font)
        self.label_age.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_age.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_age.setLineWidth(1)
        self.label_age.setTextFormat(QtCore.Qt.AutoText)
        self.label_age.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_age.setObjectName("label_age")
        self.text_age = QtWidgets.QLineEdit(self.frame_info)
        self.text_age.setEnabled(False)
        self.text_age.setGeometry(QtCore.QRect(350, 120, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_age.setFont(font)
        self.text_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_age.setInputMethodHints(QtCore.Qt.ImhNone)
        self.text_age.setText("")
        self.text_age.setAlignment(QtCore.Qt.AlignCenter)
        self.text_age.setClearButtonEnabled(False)
        self.text_age.setObjectName("text_age")
        self.button_male = QtWidgets.QRadioButton(self.frame_info)
        self.button_male.setEnabled(False)
        self.button_male.setGeometry(QtCore.QRect(80, 155, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_male.setFont(font)
        self.button_male.setStyleSheet("color: rgb(0, 0, 0);")
        self.button_male.setAutoExclusive(True)
        self.button_male.setObjectName("button_male")
        self.buttonGroup_gender = QtWidgets.QButtonGroup(PatientScreen)
        self.buttonGroup_gender.setObjectName("buttonGroup_gender")
        self.buttonGroup_gender.addButton(self.button_male)
        self.button_female = QtWidgets.QRadioButton(self.frame_info)
        self.button_female.setEnabled(False)
        self.button_female.setGeometry(QtCore.QRect(150, 155, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_female.setFont(font)
        self.button_female.setStyleSheet("color: rgb(0, 0, 0);")
        self.button_female.setAutoExclusive(True)
        self.button_female.setObjectName("button_female")
        self.buttonGroup_gender.addButton(self.button_female)
        self.button_others = QtWidgets.QRadioButton(self.frame_info)
        self.button_others.setEnabled(False)
        self.button_others.setGeometry(QtCore.QRect(210, 155, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_others.setFont(font)
        self.button_others.setStyleSheet("color: rgb(0, 0, 0);")
        self.button_others.setAutoExclusive(True)
        self.button_others.setObjectName("button_others")
        self.buttonGroup_gender.addButton(self.button_others)
        self.text_others = QtWidgets.QLineEdit(self.frame_info)
        self.text_others.setEnabled(False)
        self.text_others.setGeometry(QtCore.QRect(290, 155, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_others.setFont(font)
        self.text_others.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_others.setInputMask("")
        self.text_others.setAlignment(QtCore.Qt.AlignCenter)
        self.text_others.setClearButtonEnabled(False)
        self.text_others.setObjectName("text_others")
        self.label_work = QtWidgets.QLabel(self.frame_info)
        self.label_work.setGeometry(QtCore.QRect(0, 120, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_work.setFont(font)
        self.label_work.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_work.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_work.setLineWidth(1)
        self.label_work.setTextFormat(QtCore.Qt.AutoText)
        self.label_work.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_work.setObjectName("label_work")
        self.text_work = QtWidgets.QLineEdit(self.frame_info)
        self.text_work.setEnabled(False)
        self.text_work.setGeometry(QtCore.QRect(120, 120, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_work.setFont(font)
        self.text_work.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_work.setText("")
        self.text_work.setAlignment(QtCore.Qt.AlignCenter)
        self.text_work.setClearButtonEnabled(False)
        self.text_work.setObjectName("text_work")
        self.label_medcard = QtWidgets.QLabel(self.frame_info)
        self.label_medcard.setGeometry(QtCore.QRect(0, 190, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_medcard.setFont(font)
        self.label_medcard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_medcard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_medcard.setLineWidth(1)
        self.label_medcard.setTextFormat(QtCore.Qt.AutoText)
        self.label_medcard.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_medcard.setObjectName("label_medcard")
        self.button_noMedcard = QtWidgets.QRadioButton(self.frame_info)
        self.button_noMedcard.setEnabled(False)
        self.button_noMedcard.setGeometry(QtCore.QRect(60, 190, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_noMedcard.setFont(font)
        self.button_noMedcard.setStyleSheet("color: rgb(0, 0, 0);")
        self.button_noMedcard.setAutoExclusive(True)
        self.button_noMedcard.setObjectName("button_noMedcard")
        self.buttonGroup_medCard = QtWidgets.QButtonGroup(PatientScreen)
        self.buttonGroup_medCard.setObjectName("buttonGroup_medCard")
        self.buttonGroup_medCard.addButton(self.button_noMedcard)
        self.button_yesMedcard = QtWidgets.QRadioButton(self.frame_info)
        self.button_yesMedcard.setEnabled(False)
        self.button_yesMedcard.setGeometry(QtCore.QRect(150, 190, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_yesMedcard.setFont(font)
        self.button_yesMedcard.setStyleSheet("color: rgb(0, 0, 0);")
        self.button_yesMedcard.setAutoExclusive(True)
        self.button_yesMedcard.setObjectName("button_yesMedcard")
        self.buttonGroup_medCard.addButton(self.button_yesMedcard)
        self.text_medCardinfo = QtWidgets.QLineEdit(self.frame_info)
        self.text_medCardinfo.setEnabled(False)
        self.text_medCardinfo.setGeometry(QtCore.QRect(210, 190, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_medCardinfo.setFont(font)
        self.text_medCardinfo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_medCardinfo.setText("")
        self.text_medCardinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.text_medCardinfo.setClearButtonEnabled(False)
        self.text_medCardinfo.setObjectName("text_medCardinfo")
        self.label_admitDate = QtWidgets.QLabel(self.frame_info)
        self.label_admitDate.setGeometry(QtCore.QRect(0, 225, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_admitDate.setFont(font)
        self.label_admitDate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_admitDate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_admitDate.setLineWidth(1)
        self.label_admitDate.setTextFormat(QtCore.Qt.AutoText)
        self.label_admitDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_admitDate.setObjectName("label_admitDate")
        self.date_admitDate = QtWidgets.QDateEdit(self.frame_info)
        self.date_admitDate.setEnabled(True)
        self.date_admitDate.setGeometry(QtCore.QRect(130, 225, 125, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.date_admitDate.setFont(font)
        self.date_admitDate.setAutoFillBackground(True)
        self.date_admitDate.setStyleSheet("")
        self.date_admitDate.setReadOnly(True)
        self.date_admitDate.setAccelerated(True)
        self.date_admitDate.setCalendarPopup(True)
        self.date_admitDate.setObjectName("date_admitDate")
        self.label_treatDate = QtWidgets.QLabel(self.frame_info)
        self.label_treatDate.setGeometry(QtCore.QRect(0, 260, 175, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_treatDate.setFont(font)
        self.label_treatDate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_treatDate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_treatDate.setLineWidth(1)
        self.label_treatDate.setTextFormat(QtCore.Qt.AutoText)
        self.label_treatDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_treatDate.setObjectName("label_treatDate")
        self.date_treatDate = QtWidgets.QDateEdit(self.frame_info)
        self.date_treatDate.setEnabled(True)
        self.date_treatDate.setGeometry(QtCore.QRect(185, 260, 125, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.date_treatDate.setFont(font)
        self.date_treatDate.setAutoFillBackground(True)
        self.date_treatDate.setStyleSheet("")
        self.date_treatDate.setReadOnly(True)
        self.date_treatDate.setAccelerated(True)
        self.date_treatDate.setCalendarPopup(True)
        self.date_treatDate.setObjectName("date_treatDate")
        self.label_record = QtWidgets.QLabel(self.frame_info)
        self.label_record.setGeometry(QtCore.QRect(0, 305, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_record.setFont(font)
        self.label_record.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_record.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_record.setLineWidth(1)
        self.label_record.setTextFormat(QtCore.Qt.AutoText)
        self.label_record.setAlignment(QtCore.Qt.AlignCenter)
        self.label_record.setObjectName("label_record")
        self.text_record = QtWidgets.QTextEdit(self.frame_info)
        self.text_record.setEnabled(True)
        self.text_record.setGeometry(QtCore.QRect(0, 345, 420, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_record.setFont(font)
        self.text_record.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.text_record.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);")
        self.text_record.setReadOnly(True)
        self.text_record.setPlaceholderText("")
        self.text_record.setObjectName("text_record")
        self.label_infoBody = QtWidgets.QLabel(self.frame_info)
        self.label_infoBody.setGeometry(QtCore.QRect(0, 440, 420, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_infoBody.setFont(font)
        self.label_infoBody.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_infoBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_infoBody.setLineWidth(1)
        self.label_infoBody.setTextFormat(QtCore.Qt.AutoText)
        self.label_infoBody.setAlignment(QtCore.Qt.AlignCenter)
        self.label_infoBody.setObjectName("label_infoBody")
        self.label_weight = QtWidgets.QLabel(self.frame_info)
        self.label_weight.setGeometry(QtCore.QRect(0, 480, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_weight.setFont(font)
        self.label_weight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_weight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_weight.setLineWidth(1)
        self.label_weight.setTextFormat(QtCore.Qt.AutoText)
        self.label_weight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_weight.setObjectName("label_weight")
        self.text_weight = QtWidgets.QLineEdit(self.frame_info)
        self.text_weight.setEnabled(False)
        self.text_weight.setGeometry(QtCore.QRect(90, 480, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_weight.setFont(font)
        self.text_weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_weight.setText("")
        self.text_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.text_weight.setClearButtonEnabled(False)
        self.text_weight.setObjectName("text_weight")
        self.label_unitWeight = QtWidgets.QLabel(self.frame_info)
        self.label_unitWeight.setGeometry(QtCore.QRect(170, 480, 20, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitWeight.setFont(font)
        self.label_unitWeight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitWeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitWeight.setLineWidth(1)
        self.label_unitWeight.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitWeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitWeight.setObjectName("label_unitWeight")
        self.text_height = QtWidgets.QLineEdit(self.frame_info)
        self.text_height.setEnabled(False)
        self.text_height.setGeometry(QtCore.QRect(315, 480, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_height.setFont(font)
        self.text_height.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_height.setAlignment(QtCore.Qt.AlignCenter)
        self.text_height.setClearButtonEnabled(False)
        self.text_height.setObjectName("text_height")
        self.label_unitHeight = QtWidgets.QLabel(self.frame_info)
        self.label_unitHeight.setGeometry(QtCore.QRect(395, 480, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitHeight.setFont(font)
        self.label_unitHeight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitHeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitHeight.setLineWidth(1)
        self.label_unitHeight.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitHeight.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitHeight.setObjectName("label_unitHeight")
        self.label_height = QtWidgets.QLabel(self.frame_info)
        self.label_height.setGeometry(QtCore.QRect(220, 480, 85, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_height.setFont(font)
        self.label_height.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_height.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_height.setLineWidth(1)
        self.label_height.setTextFormat(QtCore.Qt.AutoText)
        self.label_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_height.setObjectName("label_height")
        self.label_leg = QtWidgets.QLabel(self.frame_info)
        self.label_leg.setGeometry(QtCore.QRect(0, 515, 135, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_leg.setFont(font)
        self.label_leg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_leg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_leg.setLineWidth(1)
        self.label_leg.setTextFormat(QtCore.Qt.AutoText)
        self.label_leg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_leg.setObjectName("label_leg")
        self.label_thigh = QtWidgets.QLabel(self.frame_info)
        self.label_thigh.setGeometry(QtCore.QRect(0, 550, 35, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_thigh.setFont(font)
        self.label_thigh.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_thigh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_thigh.setLineWidth(1)
        self.label_thigh.setTextFormat(QtCore.Qt.AutoText)
        self.label_thigh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_thigh.setObjectName("label_thigh")
        self.label_unitThigh = QtWidgets.QLabel(self.frame_info)
        self.label_unitThigh.setGeometry(QtCore.QRect(125, 550, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitThigh.setFont(font)
        self.label_unitThigh.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitThigh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitThigh.setLineWidth(1)
        self.label_unitThigh.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitThigh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitThigh.setObjectName("label_unitThigh")
        self.text_thigh = QtWidgets.QLineEdit(self.frame_info)
        self.text_thigh.setEnabled(False)
        self.text_thigh.setGeometry(QtCore.QRect(45, 550, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_thigh.setFont(font)
        self.text_thigh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_thigh.setAlignment(QtCore.Qt.AlignCenter)
        self.text_thigh.setClearButtonEnabled(False)
        self.text_thigh.setObjectName("text_thigh")
        self.label_shank = QtWidgets.QLabel(self.frame_info)
        self.label_shank.setGeometry(QtCore.QRect(215, 550, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_shank.setFont(font)
        self.label_shank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_shank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_shank.setLineWidth(1)
        self.label_shank.setTextFormat(QtCore.Qt.AutoText)
        self.label_shank.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_shank.setObjectName("label_shank")
        self.label_unitShank = QtWidgets.QLabel(self.frame_info)
        self.label_unitShank.setGeometry(QtCore.QRect(395, 550, 25, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_unitShank.setFont(font)
        self.label_unitShank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_unitShank.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_unitShank.setLineWidth(1)
        self.label_unitShank.setTextFormat(QtCore.Qt.AutoText)
        self.label_unitShank.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_unitShank.setObjectName("label_unitShank")
        self.text_shank = QtWidgets.QLineEdit(self.frame_info)
        self.text_shank.setEnabled(False)
        self.text_shank.setGeometry(QtCore.QRect(315, 550, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_shank.setFont(font)
        self.text_shank.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_shank.setAlignment(QtCore.Qt.AlignCenter)
        self.text_shank.setClearButtonEnabled(False)
        self.text_shank.setObjectName("text_shank")
        self.label_dispID = QtWidgets.QLabel(self.frame_info)
        self.label_dispID.setEnabled(False)
        self.label_dispID.setGeometry(QtCore.QRect(40, 85, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_dispID.setFont(font)
        self.label_dispID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);\n"
"")
        self.label_dispID.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_dispID.setText("")
        self.label_dispID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dispID.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_dispID.setObjectName("label_dispID")
        self.frame_control = QtWidgets.QFrame(self.centralwidget)
        self.frame_control.setEnabled(True)
        self.frame_control.setGeometry(QtCore.QRect(430, 80, 840, 650))
        self.frame_control.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control.setObjectName("frame_control")
        self.frame_exercises = QtWidgets.QFrame(self.frame_control)
        self.frame_exercises.setEnabled(False)
        self.frame_exercises.setGeometry(QtCore.QRect(0, 45, 560, 605))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_exercises.setFont(font)
        self.frame_exercises.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_exercises.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_exercises.setObjectName("frame_exercises")
        self.button_sineKnee = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineKnee.setGeometry(QtCore.QRect(220, 170, 120, 120))
        self.button_sineKnee.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineKnee.setFont(font)
        self.button_sineKnee.setStyleSheet("#button_sineKnee{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineKnee:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineKnee:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineKnee:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineKnee.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/sine_knee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineKnee.setIcon(icon)
        self.button_sineKnee.setIconSize(QtCore.QSize(110, 110))
        self.button_sineKnee.setObjectName("button_sineKnee")
        self.button_sineHip = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineHip.setGeometry(QtCore.QRect(50, 170, 120, 120))
        self.button_sineHip.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineHip.setFont(font)
        self.button_sineHip.setStyleSheet("#button_sineHip{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineHip:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineHip:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineHip:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineHip.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/sine_hip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineHip.setIcon(icon1)
        self.button_sineHip.setIconSize(QtCore.QSize(110, 110))
        self.button_sineHip.setObjectName("button_sineHip")
        self.button_sineAnkle = QtWidgets.QPushButton(self.frame_exercises)
        self.button_sineAnkle.setEnabled(False)
        self.button_sineAnkle.setGeometry(QtCore.QRect(390, 170, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sineAnkle.sizePolicy().hasHeightForWidth())
        self.button_sineAnkle.setSizePolicy(sizePolicy)
        self.button_sineAnkle.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sineAnkle.setFont(font)
        self.button_sineAnkle.setStyleSheet("#button_sineAnkle{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_sineAnkle:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_sineAnkle:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_sineAnkle:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_sineAnkle.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/sine_ankle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_sineAnkle.setIcon(icon2)
        self.button_sineAnkle.setIconSize(QtCore.QSize(110, 110))
        self.button_sineAnkle.setObjectName("button_sineAnkle")
        self.button_bikeEx = QtWidgets.QPushButton(self.frame_exercises)
        self.button_bikeEx.setGeometry(QtCore.QRect(220, 345, 120, 120))
        self.button_bikeEx.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_bikeEx.setFont(font)
        self.button_bikeEx.setStyleSheet("#button_bikeEx{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid rgb(110, 143, 158);\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"#button_bikeEx:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#button_bikeEx:pressed{\n"
"    background-color: rgb(240, 240, 240);\n"
" }\n"
"#button_bikeEx:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_bikeEx.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/bike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_bikeEx.setIcon(icon3)
        self.button_bikeEx.setIconSize(QtCore.QSize(110, 110))
        self.button_bikeEx.setObjectName("button_bikeEx")
        self.label_exerciseSelect = QtWidgets.QLabel(self.frame_exercises)
        self.label_exerciseSelect.setGeometry(QtCore.QRect(50, 0, 460, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_exerciseSelect.setFont(font)
        self.label_exerciseSelect.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_exerciseSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_exerciseSelect.setLineWidth(1)
        self.label_exerciseSelect.setTextFormat(QtCore.Qt.AutoText)
        self.label_exerciseSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exerciseSelect.setObjectName("label_exerciseSelect")
        self.button_sineAnkle.raise_()
        self.button_sineHip.raise_()
        self.button_bikeEx.raise_()
        self.button_sineKnee.raise_()
        self.label_exerciseSelect.raise_()
        self.frame_set = QtWidgets.QFrame(self.frame_control)
        self.frame_set.setEnabled(True)
        self.frame_set.setGeometry(QtCore.QRect(560, 200, 280, 450))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_set.setFont(font)
        self.frame_set.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_set.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_set.setObjectName("frame_set")
        self.button_start = QtWidgets.QPushButton(self.frame_set)
        self.button_start.setEnabled(False)
        self.button_start.setGeometry(QtCore.QRect(0, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("#button_start{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(21, 115, 71);\n"
"}\n"
"#button_start:hover{\n"
"    background-color: rgb(25, 135, 84);\n"
"}\n"
"#button_start:pressed{\n"
"    background-color: rgb(0, 107, 0);\n"
" }\n"
"#button_start:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(self.frame_set)
        self.button_stop.setEnabled(False)
        self.button_stop.setGeometry(QtCore.QRect(160, 330, 120, 120))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_stop.setFont(font)
        self.button_stop.setAutoFillBackground(False)
        self.button_stop.setStyleSheet("#button_stop{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(187, 43, 59);\n"
"}\n"
"#button_stop:hover{\n"
"    background-color: rgb(220, 53, 69);\n"
"}\n"
"#button_stop:pressed{\n"
"    background-color: rgb(150, 0, 0);\n"
" }\n"
"#button_stop:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_stop.setObjectName("button_stop")
        self.button_confirm = QtWidgets.QPushButton(self.frame_set)
        self.button_confirm.setEnabled(False)
        self.button_confirm.setGeometry(QtCore.QRect(80, 250, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_confirm.setFont(font)
        self.button_confirm.setStyleSheet("#button_confirm{\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    background-color: rgb(248, 152, 29);\n"
"}\n"
"#button_confirm:hover{\n"
"    background-color: rgb(255, 154, 30);\n"
"}\n"
"#button_confirm:pressed{\n"
"    background-color: rgb(255, 150, 0);\n"
" }\n"
"#button_confirm:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_confirm.setObjectName("button_confirm")
        self.button_setCycles = QtWidgets.QPushButton(self.frame_set)
        self.button_setCycles.setEnabled(False)
        self.button_setCycles.setGeometry(QtCore.QRect(0, 40, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setCycles.setFont(font)
        self.button_setCycles.setStyleSheet("")
        self.button_setCycles.setObjectName("button_setCycles")
        self.button_setTimer = QtWidgets.QPushButton(self.frame_set)
        self.button_setTimer.setEnabled(False)
        self.button_setTimer.setGeometry(QtCore.QRect(160, 40, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_setTimer.setFont(font)
        self.button_setTimer.setAutoFillBackground(False)
        self.button_setTimer.setStyleSheet("")
        self.button_setTimer.setObjectName("button_setTimer")
        self.text_cycles = QtWidgets.QLineEdit(self.frame_set)
        self.text_cycles.setEnabled(False)
        self.text_cycles.setGeometry(QtCore.QRect(0, 0, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_cycles.setFont(font)
        self.text_cycles.setInputMask("")
        self.text_cycles.setAlignment(QtCore.Qt.AlignCenter)
        self.text_cycles.setClearButtonEnabled(False)
        self.text_cycles.setObjectName("text_cycles")
        self.text_timer = QtWidgets.QTimeEdit(self.frame_set)
        self.text_timer.setEnabled(False)
        self.text_timer.setGeometry(QtCore.QRect(160, 0, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_timer.setFont(font)
        self.text_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.text_timer.setObjectName("text_timer")
        self.label_cycles = QtWidgets.QLabel(self.frame_set)
        self.label_cycles.setEnabled(False)
        self.label_cycles.setGeometry(QtCore.QRect(66, 0, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cycles.setFont(font)
        self.label_cycles.setObjectName("label_cycles")
        self.label_timer = QtWidgets.QLabel(self.frame_set)
        self.label_timer.setEnabled(False)
        self.label_timer.setGeometry(QtCore.QRect(250, 0, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_timer.setFont(font)
        self.label_timer.setObjectName("label_timer")
        self.label_exercise = QtWidgets.QLabel(self.frame_set)
        self.label_exercise.setGeometry(QtCore.QRect(0, 120, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_exercise.setFont(font)
        self.label_exercise.setText("")
        self.label_exercise.setObjectName("label_exercise")
        self.text_exercise = QtWidgets.QLabel(self.frame_set)
        self.text_exercise.setEnabled(True)
        self.text_exercise.setGeometry(QtCore.QRect(100, 120, 180, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_exercise.setFont(font)
        self.text_exercise.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_exercise.setText("")
        self.text_exercise.setAlignment(QtCore.Qt.AlignCenter)
        self.text_exercise.setWordWrap(True)
        self.text_exercise.setObjectName("text_exercise")
        self.text_cycles_timer = QtWidgets.QLabel(self.frame_set)
        self.text_cycles_timer.setGeometry(QtCore.QRect(100, 210, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.text_cycles_timer.setFont(font)
        self.text_cycles_timer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.text_cycles_timer.setText("")
        self.text_cycles_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.text_cycles_timer.setObjectName("text_cycles_timer")
        self.label_cycles_timer = QtWidgets.QLabel(self.frame_set)
        self.label_cycles_timer.setGeometry(QtCore.QRect(0, 210, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cycles_timer.setFont(font)
        self.label_cycles_timer.setText("")
        self.label_cycles_timer.setObjectName("label_cycles_timer")
        self.frame_session = QtWidgets.QFrame(self.frame_control)
        self.frame_session.setEnabled(True)
        self.frame_session.setGeometry(QtCore.QRect(560, 45, 280, 140))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_session.setFont(font)
        self.frame_session.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_session.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_session.setObjectName("frame_session")
        self.button_sessionCreate = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionCreate.setGeometry(QtCore.QRect(0, 80, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionCreate.setFont(font)
        self.button_sessionCreate.setStyleSheet("#button_sessionCreate{\n"
"    color: rgb(43, 116, 185);\n"
"    border: 2px solid rgb(43, 116, 185);\n"
"/*\n"
"    background-color: rgb(43, 116, 185);\n"
"*/\n"
"}\n"
"#button_sessionCreate:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(52, 141, 225);\n"
"*/\n"
"}\n"
"#button_sessionCreate:pressed{\n"
"    color: rgb(37, 99, 158);\n"
"    border-width: 4px;\n"
"    border-color: rgb(37, 99, 158);\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(37, 99, 158);\n"
"*/\n"
" }\n"
"#button_sessionCreate:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_sessionCreate.setObjectName("button_sessionCreate")
        self.text_sessionTitle = QtWidgets.QLineEdit(self.frame_session)
        self.text_sessionTitle.setGeometry(QtCore.QRect(0, 40, 210, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_sessionTitle.setFont(font)
        self.text_sessionTitle.setClearButtonEnabled(True)
        self.text_sessionTitle.setObjectName("text_sessionTitle")
        self.button_sessionSave = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionSave.setEnabled(False)
        self.button_sessionSave.setGeometry(QtCore.QRect(160, 80, 120, 60))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionSave.setFont(font)
        self.button_sessionSave.setStyleSheet("#button_sessionSave{\n"
"    color: rgb(184, 168, 20);\n"
"    border: 2px solid rgb(184, 168, 20);\n"
"/*\n"
"    background-color: rgb(184, 168, 20);\n"
"*/\n"
"}\n"
"#button_sessionSave:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(230, 210, 25);\n"
"*/\n"
"}\n"
"#button_sessionSave:pressed{\n"
"    color: rgb(150, 137, 16);\n"
"    border-width: 4px;\n"
"    border-color: rgb(150, 137, 16);\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(150, 137, 16);\n"
"*/\n"
" }\n"
"#button_sessionSave:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border: 2px solid rgb(208, 217, 222);\n"
"    background-color: none;\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}\n"
"")
        self.button_sessionSave.setObjectName("button_sessionSave")
        self.label_frameSession = QtWidgets.QLabel(self.frame_session)
        self.label_frameSession.setEnabled(True)
        self.label_frameSession.setGeometry(QtCore.QRect(0, 0, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_frameSession.setFont(font)
        self.label_frameSession.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_frameSession.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_frameSession.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frameSession.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_frameSession.setObjectName("label_frameSession")
        self.button_sessionEdit = QtWidgets.QPushButton(self.frame_session)
        self.button_sessionEdit.setEnabled(False)
        self.button_sessionEdit.setGeometry(QtCore.QRect(220, 40, 60, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button_sessionEdit.setFont(font)
        self.button_sessionEdit.setStyleSheet("border-radius: 10px;\n"
"")
        self.button_sessionEdit.setObjectName("button_sessionEdit")
        self.label_HUST = QtWidgets.QLabel(self.centralwidget)
        self.label_HUST.setGeometry(QtCore.QRect(10, 10, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_HUST.setFont(font)
        self.label_HUST.setStyleSheet("image: url(:/icons/icons/HUST.png);")
        self.label_HUST.setText("")
        self.label_HUST.setObjectName("label_HUST")
        self.label_Komlab = QtWidgets.QLabel(self.centralwidget)
        self.label_Komlab.setGeometry(QtCore.QRect(70, 10, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Komlab.setFont(font)
        self.label_Komlab.setStyleSheet("image: url(:/icons/icons/KomLab.png);")
        self.label_Komlab.setText("")
        self.label_Komlab.setObjectName("label_Komlab")
        self.frame_info.raise_()
        self.frame_control.raise_()
        self.button_account.raise_()
        self.button_logout.raise_()
        self.label_HUST.raise_()
        self.label_Komlab.raise_()
        PatientScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(PatientScreen)
        self.text_name.returnPressed.connect(self.text_work.setFocus) # type: ignore
        self.text_work.returnPressed.connect(self.text_age.setFocus) # type: ignore
        self.text_age.returnPressed.connect(self.button_male.setFocus) # type: ignore
        self.text_others.returnPressed.connect(self.button_noMedcard.setFocus) # type: ignore
        self.text_medCardinfo.returnPressed.connect(self.date_admitDate.setFocus) # type: ignore
        self.date_admitDate.dateChanged['QDate'].connect(self.date_treatDate.setFocus) # type: ignore
        self.date_treatDate.dateChanged['QDate'].connect(self.text_record.setFocus) # type: ignore
        self.text_weight.returnPressed.connect(self.text_height.setFocus) # type: ignore
        self.text_height.returnPressed.connect(self.text_thigh.setFocus) # type: ignore
        self.text_thigh.returnPressed.connect(self.text_shank.setFocus) # type: ignore
        self.text_shank.returnPressed.connect(self.button_infoSave.setFocus) # type: ignore
        self.button_sineHip.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_sineAnkle.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_sineKnee.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.button_bikeEx.clicked['bool'].connect(self.button_setCycles.setFocus) # type: ignore
        self.text_cycles.returnPressed.connect(self.button_setCycles.setFocus) # type: ignore
        self.text_timer.editingFinished.connect(self.button_setTimer.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PatientScreen)
        PatientScreen.setTabOrder(self.text_name, self.text_work)
        PatientScreen.setTabOrder(self.text_work, self.text_age)
        PatientScreen.setTabOrder(self.text_age, self.button_male)
        PatientScreen.setTabOrder(self.button_male, self.button_female)
        PatientScreen.setTabOrder(self.button_female, self.button_others)
        PatientScreen.setTabOrder(self.button_others, self.text_others)
        PatientScreen.setTabOrder(self.text_others, self.button_noMedcard)
        PatientScreen.setTabOrder(self.button_noMedcard, self.button_yesMedcard)
        PatientScreen.setTabOrder(self.button_yesMedcard, self.text_medCardinfo)
        PatientScreen.setTabOrder(self.text_medCardinfo, self.date_admitDate)
        PatientScreen.setTabOrder(self.date_admitDate, self.date_treatDate)
        PatientScreen.setTabOrder(self.date_treatDate, self.text_record)
        PatientScreen.setTabOrder(self.text_record, self.text_weight)
        PatientScreen.setTabOrder(self.text_weight, self.text_height)
        PatientScreen.setTabOrder(self.text_height, self.text_thigh)
        PatientScreen.setTabOrder(self.text_thigh, self.text_shank)
        PatientScreen.setTabOrder(self.text_shank, self.button_infoEdit)
        PatientScreen.setTabOrder(self.button_infoEdit, self.button_infoSave)
        PatientScreen.setTabOrder(self.button_infoSave, self.text_sessionTitle)
        PatientScreen.setTabOrder(self.text_sessionTitle, self.button_sessionEdit)
        PatientScreen.setTabOrder(self.button_sessionEdit, self.button_sessionCreate)
        PatientScreen.setTabOrder(self.button_sessionCreate, self.button_sessionSave)
        PatientScreen.setTabOrder(self.button_sessionSave, self.button_sineHip)
        PatientScreen.setTabOrder(self.button_sineHip, self.button_sineKnee)
        PatientScreen.setTabOrder(self.button_sineKnee, self.button_sineAnkle)
        PatientScreen.setTabOrder(self.button_sineAnkle, self.button_bikeEx)
        PatientScreen.setTabOrder(self.button_bikeEx, self.text_cycles)
        PatientScreen.setTabOrder(self.text_cycles, self.button_setCycles)
        PatientScreen.setTabOrder(self.button_setCycles, self.text_timer)
        PatientScreen.setTabOrder(self.text_timer, self.button_setTimer)
        PatientScreen.setTabOrder(self.button_setTimer, self.button_confirm)
        PatientScreen.setTabOrder(self.button_confirm, self.button_start)
        PatientScreen.setTabOrder(self.button_start, self.button_stop)
        PatientScreen.setTabOrder(self.button_stop, self.button_account)
        PatientScreen.setTabOrder(self.button_account, self.button_logout)

    def retranslateUi(self, PatientScreen):
        _translate = QtCore.QCoreApplication.translate
        PatientScreen.setWindowTitle(_translate("PatientScreen", "LLR_APP"))
        self.button_logout.setText(_translate("PatientScreen", "Đăng xuất"))
        self.button_account.setText(_translate("PatientScreen", "Tài khoản"))
        self.button_infoSave.setText(_translate("PatientScreen", "Lưu"))
        self.button_infoEdit.setText(_translate("PatientScreen", "Sửa"))
        self.label_infoGeneral.setText(_translate("PatientScreen", "Thông tin chung"))
        self.label_ID.setText(_translate("PatientScreen", "ID:"))
        self.label_name.setText(_translate("PatientScreen", "Họ và tên:"))
        self.label_gender.setText(_translate("PatientScreen", "Giới tính:"))
        self.label_age.setText(_translate("PatientScreen", "Tuổi:"))
        self.button_male.setText(_translate("PatientScreen", "Nam"))
        self.button_female.setText(_translate("PatientScreen", "Nữ"))
        self.button_others.setText(_translate("PatientScreen", "Khác:"))
        self.label_work.setText(_translate("PatientScreen", "Nghề nghiệp:"))
        self.label_medcard.setText(_translate("PatientScreen", "BHYT:"))
        self.button_noMedcard.setText(_translate("PatientScreen", "Không"))
        self.button_yesMedcard.setText(_translate("PatientScreen", "Có"))
        self.label_admitDate.setText(_translate("PatientScreen", "Ngày vào viện:"))
        self.label_treatDate.setText(_translate("PatientScreen", "Ngày bắt đầu điều trị:"))
        self.label_record.setText(_translate("PatientScreen", "Bệnh án"))
        self.text_record.setHtml(_translate("PatientScreen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_infoBody.setText(_translate("PatientScreen", "Nhân trắc học"))
        self.label_weight.setText(_translate("PatientScreen", "Cân nặng:"))
        self.label_unitWeight.setText(_translate("PatientScreen", "Kg"))
        self.label_unitHeight.setText(_translate("PatientScreen", "cm"))
        self.label_height.setText(_translate("PatientScreen", "Chiều cao:"))
        self.label_leg.setText(_translate("PatientScreen", "Kích thước chân:"))
        self.label_thigh.setText(_translate("PatientScreen", "Đùi:"))
        self.label_unitThigh.setText(_translate("PatientScreen", "cm"))
        self.label_shank.setText(_translate("PatientScreen", "Cẳng chân:"))
        self.label_unitShank.setText(_translate("PatientScreen", "cm"))
        self.label_exerciseSelect.setText(_translate("PatientScreen", "Lựa chọn bài tập"))
        self.button_start.setText(_translate("PatientScreen", "BẮT ĐẦU"))
        self.button_stop.setText(_translate("PatientScreen", "DỪNG"))
        self.button_confirm.setText(_translate("PatientScreen", "Xác nhận"))
        self.button_setCycles.setText(_translate("PatientScreen", "Đặt số chu kỳ"))
        self.button_setTimer.setText(_translate("PatientScreen", "Đặt thời gian"))
        self.text_timer.setDisplayFormat(_translate("PatientScreen", "mm:ss"))
        self.label_cycles.setText(_translate("PatientScreen", "chu kỳ"))
        self.label_timer.setText(_translate("PatientScreen", "m:s"))
        self.button_sessionCreate.setText(_translate("PatientScreen", "Tạo"))
        self.button_sessionSave.setText(_translate("PatientScreen", "Lưu/Báo cáo"))
        self.label_frameSession.setText(_translate("PatientScreen", "Buổi tập / Báo cáo"))
        self.button_sessionEdit.setText(_translate("PatientScreen", "Sửa"))
import resources_rc
