# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\session.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SessionDialog(object):
    def setupUi(self, SessionDialog):
        SessionDialog.setObjectName("SessionDialog")
        SessionDialog.resize(490, 440)
        self.label_sessionInfo = QtWidgets.QLabel(SessionDialog)
        self.label_sessionInfo.setGeometry(QtCore.QRect(0, 10, 485, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sessionInfo.setFont(font)
        self.label_sessionInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sessionInfo.setObjectName("label_sessionInfo")
        self.label_sessionTitle = QtWidgets.QLabel(SessionDialog)
        self.label_sessionTitle.setGeometry(QtCore.QRect(30, 60, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sessionTitle.setFont(font)
        self.label_sessionTitle.setObjectName("label_sessionTitle")
        self.text_sessionTitle = QtWidgets.QLineEdit(SessionDialog)
        self.text_sessionTitle.setGeometry(QtCore.QRect(150, 60, 310, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_sessionTitle.setFont(font)
        self.text_sessionTitle.setText("")
        self.text_sessionTitle.setCursorPosition(0)
        self.text_sessionTitle.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_sessionTitle.setObjectName("text_sessionTitle")
        self.label_sessionDay = QtWidgets.QLabel(SessionDialog)
        self.label_sessionDay.setGeometry(QtCore.QRect(30, 100, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sessionDay.setFont(font)
        self.label_sessionDay.setObjectName("label_sessionDay")
        self.label_sessionTime = QtWidgets.QLabel(SessionDialog)
        self.label_sessionTime.setGeometry(QtCore.QRect(235, 100, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sessionTime.setFont(font)
        self.label_sessionTime.setObjectName("label_sessionTime")
        self.text_patientID = QtWidgets.QLineEdit(SessionDialog)
        self.text_patientID.setGeometry(QtCore.QRect(380, 140, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_patientID.setFont(font)
        self.text_patientID.setText("")
        self.text_patientID.setCursorPosition(0)
        self.text_patientID.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_patientID.setObjectName("text_patientID")
        self.text_patient = QtWidgets.QLineEdit(SessionDialog)
        self.text_patient.setGeometry(QtCore.QRect(130, 140, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_patient.setFont(font)
        self.text_patient.setText("")
        self.text_patient.setCursorPosition(0)
        self.text_patient.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_patient.setObjectName("text_patient")
        self.label_patientID = QtWidgets.QLabel(SessionDialog)
        self.label_patientID.setGeometry(QtCore.QRect(340, 140, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_patientID.setFont(font)
        self.label_patientID.setObjectName("label_patientID")
        self.label_patient = QtWidgets.QLabel(SessionDialog)
        self.label_patient.setGeometry(QtCore.QRect(30, 140, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_patient.setFont(font)
        self.label_patient.setObjectName("label_patient")
        self.text_doctorID = QtWidgets.QLineEdit(SessionDialog)
        self.text_doctorID.setGeometry(QtCore.QRect(380, 180, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_doctorID.setFont(font)
        self.text_doctorID.setText("")
        self.text_doctorID.setCursorPosition(0)
        self.text_doctorID.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_doctorID.setObjectName("text_doctorID")
        self.label_doctor = QtWidgets.QLabel(SessionDialog)
        self.label_doctor.setGeometry(QtCore.QRect(30, 180, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_doctor.setFont(font)
        self.label_doctor.setObjectName("label_doctor")
        self.text_doctor = QtWidgets.QLineEdit(SessionDialog)
        self.text_doctor.setGeometry(QtCore.QRect(130, 180, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_doctor.setFont(font)
        self.text_doctor.setText("")
        self.text_doctor.setCursorPosition(0)
        self.text_doctor.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.text_doctor.setObjectName("text_doctor")
        self.label_doctorID = QtWidgets.QLabel(SessionDialog)
        self.label_doctorID.setGeometry(QtCore.QRect(340, 180, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_doctorID.setFont(font)
        self.label_doctorID.setObjectName("label_doctorID")
        self.label_description = QtWidgets.QLabel(SessionDialog)
        self.label_description.setGeometry(QtCore.QRect(30, 230, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_description.setFont(font)
        self.label_description.setObjectName("label_description")
        self.text_description = QtWidgets.QTextEdit(SessionDialog)
        self.text_description.setGeometry(QtCore.QRect(30, 260, 430, 90))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_description.setFont(font)
        self.text_description.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(150, 150, 150);")
        self.text_description.setObjectName("text_description")
        self.button_save = QtWidgets.QPushButton(SessionDialog)
        self.button_save.setGeometry(QtCore.QRect(185, 370, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setStyleSheet("#button_save{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_save:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_save:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_save:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_save.setObjectName("button_save")
        self.text_sessionDate = QtWidgets.QDateEdit(SessionDialog)
        self.text_sessionDate.setGeometry(QtCore.QRect(90, 100, 135, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_sessionDate.setFont(font)
        self.text_sessionDate.setAlignment(QtCore.Qt.AlignCenter)
        self.text_sessionDate.setObjectName("text_sessionDate")
        self.text_sessionTime = QtWidgets.QTimeEdit(SessionDialog)
        self.text_sessionTime.setGeometry(QtCore.QRect(325, 100, 135, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_sessionTime.setFont(font)
        self.text_sessionTime.setAlignment(QtCore.Qt.AlignCenter)
        self.text_sessionTime.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.text_sessionTime.setCalendarPopup(False)
        self.text_sessionTime.setTimeSpec(QtCore.Qt.LocalTime)
        self.text_sessionTime.setObjectName("text_sessionTime")

        self.retranslateUi(SessionDialog)
        QtCore.QMetaObject.connectSlotsByName(SessionDialog)
        SessionDialog.setTabOrder(self.text_sessionTitle, self.text_sessionDate)
        SessionDialog.setTabOrder(self.text_sessionDate, self.text_sessionTime)
        SessionDialog.setTabOrder(self.text_sessionTime, self.text_patient)
        SessionDialog.setTabOrder(self.text_patient, self.text_patientID)
        SessionDialog.setTabOrder(self.text_patientID, self.text_doctor)
        SessionDialog.setTabOrder(self.text_doctor, self.text_doctorID)
        SessionDialog.setTabOrder(self.text_doctorID, self.text_description)
        SessionDialog.setTabOrder(self.text_description, self.button_save)

    def retranslateUi(self, SessionDialog):
        _translate = QtCore.QCoreApplication.translate
        SessionDialog.setWindowTitle(_translate("SessionDialog", "SESSION"))
        self.label_sessionInfo.setText(_translate("SessionDialog", "Thông tin buổi tập"))
        self.label_sessionTitle.setText(_translate("SessionDialog", "Tên buổi tập:"))
        self.label_sessionDay.setText(_translate("SessionDialog", "Ngày:"))
        self.label_sessionTime.setText(_translate("SessionDialog", "Thời gian:"))
        self.label_patientID.setText(_translate("SessionDialog", "ID:"))
        self.label_patient.setText(_translate("SessionDialog", "Bệnh nhân:"))
        self.label_doctor.setText(_translate("SessionDialog", "Bác sỹ:"))
        self.label_doctorID.setText(_translate("SessionDialog", "ID:"))
        self.label_description.setText(_translate("SessionDialog", "Mô tả:"))
        self.text_description.setPlaceholderText(_translate("SessionDialog", "Nhập mô tả..."))
        self.button_save.setText(_translate("SessionDialog", "Lưu"))
        self.text_sessionTime.setDisplayFormat(_translate("SessionDialog", "hh:mm:ss"))
