# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\set_angle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetAngleDialog(object):
    def setupUi(self, SetAngleDialog):
        SetAngleDialog.setObjectName("SetAngleDialog")
        SetAngleDialog.resize(280, 220)
        self.label_title = QtWidgets.QLabel(SetAngleDialog)
        self.label_title.setGeometry(QtCore.QRect(0, 10, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.text_angle = QtWidgets.QLineEdit(SetAngleDialog)
        self.text_angle.setGeometry(QtCore.QRect(100, 100, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_angle.setFont(font)
        self.text_angle.setText("")
        self.text_angle.setCursorPosition(0)
        self.text_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.text_angle.setObjectName("text_angle")
        self.button_save = QtWidgets.QPushButton(SetAngleDialog)
        self.button_save.setGeometry(QtCore.QRect(80, 150, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setStyleSheet("#button_save{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_save:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_save:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_save:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_save.setObjectName("button_save")
        self.label_joint = QtWidgets.QLabel(SetAngleDialog)
        self.label_joint.setGeometry(QtCore.QRect(0, 50, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_joint.setFont(font)
        self.label_joint.setText("")
        self.label_joint.setAlignment(QtCore.Qt.AlignCenter)
        self.label_joint.setObjectName("label_joint")
        self.label_unitJoint = QtWidgets.QLabel(SetAngleDialog)
        self.label_unitJoint.setGeometry(QtCore.QRect(190, 100, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_unitJoint.setFont(font)
        self.label_unitJoint.setObjectName("label_unitJoint")

        self.retranslateUi(SetAngleDialog)
        QtCore.QMetaObject.connectSlotsByName(SetAngleDialog)
        SetAngleDialog.setTabOrder(self.text_angle, self.button_save)

    def retranslateUi(self, SetAngleDialog):
        _translate = QtCore.QCoreApplication.translate
        SetAngleDialog.setWindowTitle(_translate("SetAngleDialog", "SET ANGLE"))
        self.label_title.setText(_translate("SetAngleDialog", "Đặt thông số góc khớp"))
        self.button_save.setText(_translate("SetAngleDialog", "Lưu"))
        self.label_unitJoint.setText(_translate("SetAngleDialog", "<html><head/><body><p>độ(<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
