# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\set_sine.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetSineDialog(object):
    def setupUi(self, SetSineDialog):
        SetSineDialog.setObjectName("SetSineDialog")
        SetSineDialog.resize(380, 340)
        self.label_sessionInfo = QtWidgets.QLabel(SetSineDialog)
        self.label_sessionInfo.setGeometry(QtCore.QRect(0, 10, 380, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sessionInfo.setFont(font)
        self.label_sessionInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sessionInfo.setObjectName("label_sessionInfo")
        self.text_amplitude = QtWidgets.QLineEdit(SetSineDialog)
        self.text_amplitude.setGeometry(QtCore.QRect(200, 100, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_amplitude.setFont(font)
        self.text_amplitude.setText("")
        self.text_amplitude.setCursorPosition(0)
        self.text_amplitude.setAlignment(QtCore.Qt.AlignCenter)
        self.text_amplitude.setObjectName("text_amplitude")
        self.button_save = QtWidgets.QPushButton(SetSineDialog)
        self.button_save.setGeometry(QtCore.QRect(60, 270, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_save.setFont(font)
        self.button_save.setStyleSheet("#button_save{\n"
"    color: rgb(0, 170, 255);\n"
"    border: 2px solid rgb(0, 170, 255);\n"
"/*\n"
"    background-color: rgb(0, 170, 255);\n"
"*/\n"
"}\n"
"#button_save:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(100, 200, 255);\n"
"*/\n"
"}\n"
"#button_save:pressed{\n"
"    color: rgb(0, 85, 255);\n"
"    border-width: 4px;\n"
"    border-color: rgb(0, 85, 255),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(0, 85, 255);\n"
"*/\n"
" }\n"
"#button_save:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_save.setObjectName("button_save")
        self.label_joint = QtWidgets.QLabel(SetSineDialog)
        self.label_joint.setGeometry(QtCore.QRect(0, 50, 380, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_joint.setFont(font)
        self.label_joint.setText("")
        self.label_joint.setAlignment(QtCore.Qt.AlignCenter)
        self.label_joint.setObjectName("label_joint")
        self.label_unitAmplitude = QtWidgets.QLabel(SetSineDialog)
        self.label_unitAmplitude.setGeometry(QtCore.QRect(290, 100, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_unitAmplitude.setFont(font)
        self.label_unitAmplitude.setObjectName("label_unitAmplitude")
        self.label_amplitude = QtWidgets.QLabel(SetSineDialog)
        self.label_amplitude.setGeometry(QtCore.QRect(60, 100, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_amplitude.setFont(font)
        self.label_amplitude.setObjectName("label_amplitude")
        self.label_unitCycle = QtWidgets.QLabel(SetSineDialog)
        self.label_unitCycle.setEnabled(False)
        self.label_unitCycle.setGeometry(QtCore.QRect(290, 140, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_unitCycle.setFont(font)
        self.label_unitCycle.setObjectName("label_unitCycle")
        self.label_cycle = QtWidgets.QLabel(SetSineDialog)
        self.label_cycle.setEnabled(False)
        self.label_cycle.setGeometry(QtCore.QRect(60, 140, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cycle.setFont(font)
        self.label_cycle.setObjectName("label_cycle")
        self.text_cycle = QtWidgets.QLineEdit(SetSineDialog)
        self.text_cycle.setEnabled(False)
        self.text_cycle.setGeometry(QtCore.QRect(200, 140, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_cycle.setFont(font)
        self.text_cycle.setText("")
        self.text_cycle.setCursorPosition(0)
        self.text_cycle.setAlignment(QtCore.Qt.AlignCenter)
        self.text_cycle.setObjectName("text_cycle")
        self.label_unitPhase = QtWidgets.QLabel(SetSineDialog)
        self.label_unitPhase.setEnabled(False)
        self.label_unitPhase.setGeometry(QtCore.QRect(290, 180, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_unitPhase.setFont(font)
        self.label_unitPhase.setObjectName("label_unitPhase")
        self.label_phase = QtWidgets.QLabel(SetSineDialog)
        self.label_phase.setEnabled(False)
        self.label_phase.setGeometry(QtCore.QRect(60, 180, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.text_phase = QtWidgets.QLineEdit(SetSineDialog)
        self.text_phase.setEnabled(False)
        self.text_phase.setGeometry(QtCore.QRect(200, 180, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_phase.setFont(font)
        self.text_phase.setText("")
        self.text_phase.setCursorPosition(0)
        self.text_phase.setAlignment(QtCore.Qt.AlignCenter)
        self.text_phase.setObjectName("text_phase")
        self.label_unitBias = QtWidgets.QLabel(SetSineDialog)
        self.label_unitBias.setEnabled(False)
        self.label_unitBias.setGeometry(QtCore.QRect(290, 220, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_unitBias.setFont(font)
        self.label_unitBias.setObjectName("label_unitBias")
        self.text_bias = QtWidgets.QLineEdit(SetSineDialog)
        self.text_bias.setEnabled(False)
        self.text_bias.setGeometry(QtCore.QRect(200, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_bias.setFont(font)
        self.text_bias.setText("")
        self.text_bias.setCursorPosition(0)
        self.text_bias.setAlignment(QtCore.Qt.AlignCenter)
        self.text_bias.setObjectName("text_bias")
        self.label_bias = QtWidgets.QLabel(SetSineDialog)
        self.label_bias.setEnabled(False)
        self.label_bias.setGeometry(QtCore.QRect(60, 220, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_bias.setFont(font)
        self.label_bias.setObjectName("label_bias")
        self.button_setDefault = QtWidgets.QPushButton(SetSineDialog)
        self.button_setDefault.setGeometry(QtCore.QRect(200, 270, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_setDefault.setFont(font)
        self.button_setDefault.setStyleSheet("#button_setDefault{\n"
"    color: rgb(129, 20, 184);\n"
"    border: 2px solid rgb(129, 20, 184);\n"
"/*\n"
"    background-color: rgb(129, 20, 184);\n"
"    color: rgb(255, 255, 255);\n"
"*/\n"
"}\n"
"#button_setDefault:hover{\n"
"    border-width: 4px;\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(162, 26, 235);\n"
"*/\n"
"}\n"
"#button_setDefault:pressed{\n"
"    color: rgb(97, 15, 141);\n"
"    border-width: 4px;\n"
"    border-color: rgb(97, 15, 141),\n"
"/*\n"
"    border-color: rgb(6, 121, 213);\n"
"    background-color: rgb(97, 15, 141);\n"
"*/\n"
" }\n"
"#button_setDefault:disabled{\n"
"    color: rgb(208, 217, 222);\n"
"    border-color: rgb(208, 217, 222);\n"
"/*\n"
"    color: rgb(170, 170, 170);\n"
"    border-color: rgb(170, 170, 170);\n"
"    background-color: rgb(240, 240, 240);\n"
"*/\n"
"}")
        self.button_setDefault.setObjectName("button_setDefault")

        self.retranslateUi(SetSineDialog)
        QtCore.QMetaObject.connectSlotsByName(SetSineDialog)
        SetSineDialog.setTabOrder(self.text_amplitude, self.text_cycle)
        SetSineDialog.setTabOrder(self.text_cycle, self.text_phase)
        SetSineDialog.setTabOrder(self.text_phase, self.text_bias)
        SetSineDialog.setTabOrder(self.text_bias, self.button_save)

    def retranslateUi(self, SetSineDialog):
        _translate = QtCore.QCoreApplication.translate
        SetSineDialog.setWindowTitle(_translate("SetSineDialog", "SET TRAJECTORY"))
        self.label_sessionInfo.setText(_translate("SetSineDialog", "Đặt thông số quỹ đạo góc khớp"))
        self.button_save.setText(_translate("SetSineDialog", "Lưu"))
        self.label_unitAmplitude.setText(_translate("SetSineDialog", "<html><head/><body><p>độ(<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
        self.label_amplitude.setText(_translate("SetSineDialog", "Biên độ:"))
        self.label_unitCycle.setText(_translate("SetSineDialog", "<html><head/><body><p>giây(s)</p></body></html>"))
        self.label_cycle.setText(_translate("SetSineDialog", "Chu kỳ:"))
        self.label_unitPhase.setText(_translate("SetSineDialog", "<html><head/><body><p>độ(<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
        self.label_phase.setText(_translate("SetSineDialog", "Pha trễ:"))
        self.label_unitBias.setText(_translate("SetSineDialog", "<html><head/><body><p>độ(<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
        self.label_bias.setText(_translate("SetSineDialog", "Pha ban đầu:"))
        self.button_setDefault.setText(_translate("SetSineDialog", "Đặt mặc định"))
